#!/bin/bash
# ============================================================================
# deploy_lab_v13.sh — Data Center CLOS Lab Deployment (KVM / WSL2)
# ============================================================================
# Generated by: GitHub Copilot (Claude Opus 4.6)
# Date:         2026-04-30
# Version:      13.0 (Definitive — consolidates v1–v12 features)
# ============================================================================
#
# EVOLUTION:
#   v1-v2:  Basic virt-install, auto-download, ping validation
#   v3-v4:  Integrity checks, SHA256 verification
#   v5-v6:  Auto-install deps, SSH validation, Ansible inventory generation
#   v7-v8:  COW backing disks, force-delete, permission fixes
#   v9:     Download→verify→process pipeline, images dir wipe
#   v10:    Corporate proxy support (wget/curl), configurable disk format
#   v11:    Interactive format selection, serial console, --virt-type kvm
#   v12:    Cloud-init via genisoimage, per-VM credentials
#   v13:    ALL OF THE ABOVE + OVS fabric wiring + teardown/status modes
#           + SSH validation with retries + profile-aware resource budgeting
#
# TOPOLOGY (from TopologyRequirements.txt):
#   Spines:        Spine_S1, Spine_S2
#   Leafs:         Leaf_L1, Leaf_L2, Leaf_L3, Leaf_L4
#   Border Leafs:  Border_Leaf1, Border_Leaf2
#   Exit Router:   Exit_Router1, Exit_Router2 (MikroTik CHR CRS326)
#   Mgmt Switch:   OVS bridge (no dedicated VM)
#   Servers:       Host12_1, Host12_2, Host12_3, Host34_1, Host34_2, HostB12_1
#                  (16 VMs total)
#
# AUTOMATION PROFILES:
#   win11_kvm        Windows 11 / WSL lab profile (23 GB total guest RAM)
#   ubuntu_r620_kvm  Ubuntu / Dell R620 lab profile (82 GB total guest RAM)
#   real_hardware    Physical-switch profile; no KVM lab deployment
#
# USAGE:
#   bash deploy_lab_v13.sh [--profile <name>] <action> [targets]
#
#   Actions:
#     deploy    [targets] — Full lab build (idempotent)
#     redeploy  [targets] — Force-delete + fresh deploy
#     destroy   [targets] — Tear down (full teardown if no targets)
#     validate  [targets] — SSH validation only
#     test      <type>    — Deploy single test VM (sonic|ubuntu|chr) + auto-SSH
#     ssh       <vm>      — SSH directly into a VM
#     console   <vm>      — Attach virsh console to a VM
#     status              — Show VM states and connectivity
#     images              — Download/verify images only
#
#   Targets (optional, default=all):
#     Single:   Spine_S1, Leaf_L2, Host12_1
#     Multiple: Spine_S1,Leaf_L1  (comma-separated)
#     Groups:   spines, leafs, border_leafs, switches, servers, router, all
#
# PROXY: Uses corporate proxy (AT&T) for all downloads.
# ============================================================================
set -euo pipefail

# ======================= PROXY CONFIGURATION ================================
export WSL_PAC_URL="http://autoproxy.sbc.com/autoproxy.cgi"
export HTTP_PROXY="${HTTP_PROXY:-http://cso.proxy.att.com:8080}"
export HTTPS_PROXY="${HTTPS_PROXY:-http://cso.proxy.att.com:8080}"
export http_proxy="$HTTP_PROXY"
export https_proxy="$HTTPS_PROXY"
export no_proxy="localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"

# ======================= CONFIGURATION ======================================

LAB_ROOT="${LAB_ROOT:-$HOME/dc_lab}"
PROJECT_ROOT="${PROJECT_ROOT:-$HOME/dc_lab_project}"
IMG_DIR="$LAB_ROOT/images"
TMP_DIR="$LAB_ROOT/tmp"
DISK_DIR="$LAB_ROOT/disks"
CLOUD_INIT_DIR="$LAB_ROOT/cloud-init"
LOG_FILE="$LAB_ROOT/deploy_$(date +%Y%m%d_%H%M%S).log"
INVENTORY_FILE="$PROJECT_ROOT/inventory.yml"

# --- Image URLs (SONiC 202405 branch latest build, Ubuntu Noble, CHR 7.16) ---
SONIC_URL="https://sonic-build.azurewebsites.net/api/sonic/artifacts?branchName=202405&platform=vs&target=target%2Fsonic-vs.img.gz"
UBUNTU_URL="https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
CHR_URL="https://download.mikrotik.com/routeros/7.16/chr-7.16.img.zip"

# --- SHA256 verification ---
CHR_SHA256="b1701c1da14015908e0bb36deae022905e085fc59e0670be83261bdb660030ed"

# --- VM Resource Profiles ---
AUTOMATION_PROFILE="${AUTOMATION_PROFILE:-}"
AUTOMATION_PROFILE_LABEL=""
PROFILE_IS_LAB=true
SONIC_RAM=2048;  SONIC_VCPU=2; SONIC_NICS=32
SERVER_RAM=1024; SERVER_VCPU=2; SERVER_NICS=4
CHR_RAM=512;     CHR_VCPU=1;   CHR_NICS=2

# --- Configurable SONiC Disk Format (qcow2 or raw) ---
SONIC_DISK_FORMAT="${SONIC_DISK_FORMAT:-qcow2}"

# --- Management Network (libvirt NAT for SSH from host) ---
MGMT_NET_NAME="dc-mgmt"
MGMT_NET_GW="172.16.2.1"
MGMT_DHCP_START="172.16.2.10"
MGMT_DHCP_END="172.16.2.100"

# --- SSH validation tuning ---
SSH_MAX_RETRIES=15
SSH_RETRY_DELAY=10
SSH_TIMEOUT=5

# ======================= COLOUR HELPERS =====================================
RED='\033[0;31m'; GRN='\033[0;32m'; YLW='\033[0;33m'; CYN='\033[0;36m'
BLD='\033[1m'; RST='\033[0m'
log()     { echo -e "${CYN}[$(date '+%H:%M:%S')]${RST} $1" | tee -a "$LOG_FILE"; }
ok()      { echo -e "${GRN}[  OK  ]${RST} $1" | tee -a "$LOG_FILE"; }
warn()    { echo -e "${YLW}[ WARN ]${RST} $1" | tee -a "$LOG_FILE"; }
err()     { echo -e "${RED}[ERROR ]${RST} $1" | tee -a "$LOG_FILE"; }
die()     { err "$1"; exit 1; }
header()  { echo -e "\n${BLD}${CYN}══════ $1 ══════${RST}\n" | tee -a "$LOG_FILE"; }

# ======================= TOPOLOGY MAP =======================================

declare -A VM_TYPE VM_RAM VM_VCPU VM_NICS

apply_profile_settings() {
    local profile="$1"

    case "$profile" in
        win11_kvm)
            AUTOMATION_PROFILE_LABEL="QEMU/KVM on Windows 11"
            PROFILE_IS_LAB=true
            SONIC_RAM=4096;  SONIC_VCPU=4
            SERVER_RAM=1024; SERVER_VCPU=2
            CHR_RAM=512;     CHR_VCPU=1
            ;;
        ubuntu_r620_kvm)
            AUTOMATION_PROFILE_LABEL="QEMU/KVM on Ubuntu for Dell R620"
            PROFILE_IS_LAB=true
            SONIC_RAM=4096;  SONIC_VCPU=2
            SERVER_RAM=8192; SERVER_VCPU=4
            CHR_RAM=1024;    CHR_VCPU=1
            ;;
        real_hardware)
            AUTOMATION_PROFILE_LABEL="Real hardware"
            PROFILE_IS_LAB=false
            SONIC_RAM=0; SERVER_RAM=0; CHR_RAM=0
            SONIC_VCPU=0; SERVER_VCPU=0; CHR_VCPU=0
            ;;
        *)
            die "Unsupported profile '$profile'. Use: win11_kvm, ubuntu_r620_kvm, real_hardware"
            ;;
    esac

    AUTOMATION_PROFILE="$profile"
    export AUTOMATION_PROFILE
}

prompt_for_profile() {
    local choice

    echo "Select automation profile:"
    echo "  1) win11_kvm        - QEMU/KVM on Windows 11"
    echo "  2) ubuntu_r620_kvm  - QEMU/KVM on Ubuntu for Dell R620"
    echo "  3) real_hardware    - Physical hardware (no KVM lab deployment)"
    read -r -p "Profile [1]: " choice

    case "${choice:-1}" in
        1) apply_profile_settings "win11_kvm" ;;
        2) apply_profile_settings "ubuntu_r620_kvm" ;;
        3) apply_profile_settings "real_hardware" ;;
        *) die "Invalid profile selection: ${choice}" ;;
    esac
}

initialize_vm_catalog() {
    VM_TYPE=()
    VM_RAM=()
    VM_VCPU=()
    VM_NICS=()

    # --- Switches (8 SONiC) ---
    for sw in Spine_S1 Spine_S2 Leaf_L1 Leaf_L2 Leaf_L3 Leaf_L4 Border_Leaf1 Border_Leaf2; do
        VM_TYPE[$sw]="sonic"; VM_RAM[$sw]=$SONIC_RAM; VM_VCPU[$sw]=$SONIC_VCPU; VM_NICS[$sw]=$SONIC_NICS
    done

    # --- Servers (7 Ubuntu) ---
    for sv in Host12_1 Host12_2 Host12_3 Host34_1 Host34_2 HostB12_1 HostB12_2; do
        VM_TYPE[$sv]="ubuntu"; VM_RAM[$sv]=$SERVER_RAM; VM_VCPU[$sv]=$SERVER_VCPU; VM_NICS[$sv]=$SERVER_NICS
    done

    # --- Exit Routers (2 MikroTik CHR CRS326) ---
    for er in Exit_Router1 Exit_Router2; do
        VM_TYPE[$er]="chr"; VM_RAM[$er]=$CHR_RAM; VM_VCPU[$er]=$CHR_VCPU; VM_NICS[$er]=$CHR_NICS
    done
}

print_profile_summary() {
    local total_ram_mb

    if $PROFILE_IS_LAB; then
        total_ram_mb=$((8 * SONIC_RAM + 7 * SERVER_RAM + 2 * CHR_RAM))
        log "Profile: $AUTOMATION_PROFILE ($AUTOMATION_PROFILE_LABEL)"
        log "Resource plan: SONiC=${SONIC_RAM}MB x8, Ubuntu=${SERVER_RAM}MB x7, CHR=${CHR_RAM}MB x2 => ${total_ram_mb}MB guest RAM"
    else
        log "Profile: $AUTOMATION_PROFILE ($AUTOMATION_PROFILE_LABEL)"
        log "This profile skips KVM lab deployment and is intended for Ansible playbooks against physical switches."
    fi
}

require_lab_profile() {
    local action="$1"

    if ! $PROFILE_IS_LAB; then
        case "$action" in
            destroy|--destroy)
                return 0
                ;;
            *)
                die "The real_hardware profile does not create or manage KVM lab VMs. Run the Ansible playbooks with AUTOMATION_PROFILE=real_hardware instead."
                ;;
        esac
    fi
}

# --- Ordered deployment sequence ---
VM_DEPLOY_ORDER=(
    Spine_S1 Spine_S2
    Leaf_L1 Leaf_L2 Leaf_L3 Leaf_L4
    Border_Leaf1 Border_Leaf2
    Exit_Router1 Exit_Router2
    Host12_1 Host12_2 Host12_3 Host34_1 Host34_2 HostB12_1 HostB12_2
)

# --- Fabric point-to-point OVS bridges (26 total) ---
FABRIC_BRIDGES=(
    # Isolated null bridge for NIC-index padding (Accton @49 leaves use br-pad to
    # create real virtio NICs at positions 4-52 so that QSFP+ uplinks land on
    # NIC53/54 = port_config.ini index=53/54 = Ethernet64/68).
    "br-pad"
    # Leaf ↔ Spine (8 links)
    "br-L1-S1" "br-L1-S2"
    "br-L2-S1" "br-L2-S2"
    "br-L3-S1" "br-L3-S2"
    "br-L4-S1" "br-L4-S2"
    # Border-Leaf ↔ Spine (4 links)
    "br-BL1-S1" "br-BL1-S2"
    "br-BL2-S1" "br-BL2-S2"
    # Border-Leaf ↔ Exit Router (2 links: each border-leaf to its own exit router)
    "br-BL1-ER1" "br-BL2-ER2"
    # Server dual-home links (12 links)
    "br-H121-L1" "br-H121-L2"
    "br-H122-L1" "br-H122-L2"
    "br-H123-L1" "br-H123-L2"
    "br-H341-L3" "br-H341-L4"
    "br-H342-L3" "br-H342-L4"
    "br-HB-BL1"  "br-HB-BL2"
    "br-HB2-BL1" "br-HB2-BL2"
)

# --- VM → fabric bridge map (NIC0=mgmt, NIC1+=fabric) ---
declare -A VM_BRIDGES
VM_BRIDGES[Spine_S1]="br-L1-S1,br-L2-S1,br-L3-S1,br-L4-S1,br-BL1-S1,br-BL2-S1"
VM_BRIDGES[Spine_S2]="br-L1-S2,br-L2-S2,br-L3-S2,br-L4-S2,br-BL1-S2,br-BL2-S2"
# Accton AS5712-54X leaf wiring — SEQUENTIAL port_config.ini mapping on KVM VS:
#   port_config.ini has 72 ports (48 SFP+ + 6×4 QSFP+ sub-ports, all pre-broken-out).
#   KVM VS maps port N in port_config.ini to kernel interface ethN (NIC-N).
#   The `index` field in port_config.ini is physical cage metadata, NOT the NIC binding.
#
#   NIC1-3:   host downlinks (Ethernet0-2 = SFP+ ports, port_config.ini positions 1-3)
#   @61:      pad NIC4-64  (positions 4-64 = Ethernet3-Ethernet63, unused in lab)
#   NIC65:    Spine_S2 uplink (Ethernet64 = QSFP+5 sub-port, port_config.ini position 65)
#   @3:       pad NIC66-68 (positions 66-68 = Ethernet65-67, unused QSFP+5 sub-ports)
#   NIC69:    Spine_S1 uplink (Ethernet68 = QSFP+6 sub-port, port_config.ini position 69)
#   @3:       pad NIC70-72 (positions 70-72 = Ethernet69-71, unused QSFP+6 sub-ports)
#   Total: 3 + 61 + 1 + 3 + 1 + 3 = 72 data NICs + 1 mgmt = 73 NICs per Accton leaf.
VM_BRIDGES[Leaf_L1]="br-H121-L1,br-H122-L1,br-H123-L1,@61,br-L1-S2,@3,br-L1-S1,@3"
VM_BRIDGES[Leaf_L2]="br-H121-L2,br-H122-L2,br-H123-L2,@61,br-L2-S2,@3,br-L2-S1,@3"
# Arista 7050QX-32/32S leaf and border-leaf wiring — port_config.ini mapping on KVM VS:
#   port_config.ini has 32 QSFP+ ports (stride 4): Ethernet0,4,8,...,124
#   KVM VS maps port N in port_config.ini to kernel interface ethN (NIC-N).
#
#   Leaf_L3/L4 layout (32 data NICs):
#     NIC1-2:   host downlinks  (pos 1-2 = Ethernet0, Ethernet4)
#               NOTE: On physical hardware w/ QSFP+1 4x10G breakout, pos 2 would be
#               Ethernet1 (L3) or Ethernet2 (L4). KVM VS uses native → Ethernet4.
#     @28:      pad NIC3-30     (pos 3-30 = Ethernet8-Ethernet116, unused)
#     NIC31:    Spine_S2 uplink (pos 31 = Ethernet120 = QSFP+31)
#     NIC32:    Spine_S1 uplink (pos 32 = Ethernet124 = QSFP+32)
#     Total: 2 + 28 + 2 = 32 data NICs + 1 mgmt = 33 NICs per Arista leaf.
#
#   Border_Leaf1 layout (32 data NICs):
#     NIC1:     Exit_Router1    (pos 1 = Ethernet0 = QSFP+1, 4x10G breakout)
#     @4:       pad NIC2-5      (pos 2-5 = Ethernet4-Ethernet16, unused)
#     NIC6:     HostB12_1       (pos 6 = Ethernet20 = QSFP+6)
#     NIC7:     HostB12_2       (pos 7 = Ethernet24 = QSFP+7)
#               NOTE: On physical hardware w/ QSFP+6 4x10G breakout, this would be
#               Ethernet21 (sub1). KVM VS uses native port_config.ini → Ethernet24.
#     @23:      pad NIC8-30     (pos 8-30 = Ethernet28-Ethernet116, unused)
#     NIC31:    Spine_S2 uplink (pos 31 = Ethernet120 = QSFP+31)
#     NIC32:    Spine_S1 uplink (pos 32 = Ethernet124 = QSFP+32)
#     Total: 1 + 4 + 1 + 1 + 23 + 2 = 32 data NICs + 1 mgmt = 33 NICs.
#
#   Border_Leaf2 layout (32 data NICs):
#     NIC1:     Exit_Router2    (pos 1 = Ethernet0 = QSFP+1, 4x10G breakout)
#     @4:       pad NIC2-5      (pos 2-5 = Ethernet4-Ethernet16, unused)
#     NIC6:     HostB12_1       (pos 6 = Ethernet20 = QSFP+6)
#     NIC7:     HostB12_2       (pos 7 = Ethernet24 = QSFP+7)
#               NOTE: On physical hardware w/ QSFP+6 4x10G breakout, this would be
#               Ethernet21 (sub1). KVM VS uses native port_config.ini → Ethernet24.
#     @23:      pad NIC8-30     (pos 8-30 = Ethernet28-Ethernet116, unused)
#     NIC31:    Spine_S2 uplink (pos 31 = Ethernet120 = QSFP+31)
#     NIC32:    Spine_S1 uplink (pos 32 = Ethernet124 = QSFP+32)
#     Total: 1 + 4 + 1 + 1 + 23 + 2 = 32 data NICs + 1 mgmt = 33 NICs.
VM_BRIDGES[Leaf_L3]="br-H341-L3,br-H342-L3,@28,br-L3-S2,br-L3-S1"
VM_BRIDGES[Leaf_L4]="br-H341-L4,br-H342-L4,@28,br-L4-S2,br-L4-S1"
VM_BRIDGES[Border_Leaf1]="br-BL1-ER1,@4,br-HB-BL1,br-HB2-BL1,@23,br-BL1-S2,br-BL1-S1"
VM_BRIDGES[Border_Leaf2]="br-BL2-ER2,@4,br-HB-BL2,br-HB2-BL2,@23,br-BL2-S2,br-BL2-S1"
VM_BRIDGES[Exit_Router1]="br-BL1-ER1"
VM_BRIDGES[Exit_Router2]="br-BL2-ER2"
VM_BRIDGES[Host12_1]="br-H121-L1,br-H121-L2"
VM_BRIDGES[Host12_2]="br-H122-L1,br-H122-L2"
VM_BRIDGES[Host12_3]="br-H123-L1,br-H123-L2"
VM_BRIDGES[Host34_1]="br-H341-L3,br-H341-L4"
VM_BRIDGES[Host34_2]="br-H342-L3,br-H342-L4"
VM_BRIDGES[HostB12_1]="br-HB-BL1,br-HB-BL2"
VM_BRIDGES[HostB12_2]="br-HB2-BL1,br-HB2-BL2"

# --- Management IPs (static DHCP) ---
declare -A VM_MGMT_IP
VM_MGMT_IP[Spine_S1]="172.16.2.11";   VM_MGMT_IP[Spine_S2]="172.16.2.12"
VM_MGMT_IP[Leaf_L1]="172.16.2.21";    VM_MGMT_IP[Leaf_L2]="172.16.2.22"
VM_MGMT_IP[Leaf_L3]="172.16.2.23";    VM_MGMT_IP[Leaf_L4]="172.16.2.24"
VM_MGMT_IP[Border_Leaf1]="172.16.2.31"; VM_MGMT_IP[Border_Leaf2]="172.16.2.32"
VM_MGMT_IP[Exit_Router1]="172.16.2.98"; VM_MGMT_IP[Exit_Router2]="172.16.2.99"
VM_MGMT_IP[Host12_1]="172.16.2.40";   VM_MGMT_IP[Host12_2]="172.16.2.41"
VM_MGMT_IP[Host12_3]="172.16.2.42";   VM_MGMT_IP[Host34_1]="172.16.2.43"
VM_MGMT_IP[Host34_2]="172.16.2.44";   VM_MGMT_IP[HostB12_1]="172.16.2.45"
VM_MGMT_IP[HostB12_2]="172.16.2.46"

# --- Credentials per VM type ---
declare -A VM_USER VM_PASS
VM_USER[sonic]="admin";   VM_PASS[sonic]="amolla01"
VM_USER[ubuntu]="ubuntu"; VM_PASS[ubuntu]="ubuntu"
VM_USER[chr]="admin";     VM_PASS[chr]=""

# --- Server Loopback IPs (announced via FRR BGP, pingable from everywhere) ---
declare -A SERVER_LOOPBACK_IP SERVER_BGP_ASN SERVER_ROUTER_ID
SERVER_LOOPBACK_IP[Host12_1]="10.10.255.1/32";   SERVER_ROUTER_ID[Host12_1]="10.10.255.1"
SERVER_LOOPBACK_IP[Host12_2]="10.10.255.2/32";   SERVER_ROUTER_ID[Host12_2]="10.10.255.2"
SERVER_LOOPBACK_IP[Host12_3]="10.10.255.3/32";   SERVER_ROUTER_ID[Host12_3]="10.10.255.3"
SERVER_LOOPBACK_IP[Host34_1]="10.10.255.11/32";  SERVER_ROUTER_ID[Host34_1]="10.10.255.11"
SERVER_LOOPBACK_IP[Host34_2]="10.10.255.12/32";  SERVER_ROUTER_ID[Host34_2]="10.10.255.12"
SERVER_LOOPBACK_IP[HostB12_1]="10.10.255.100/32"; SERVER_ROUTER_ID[HostB12_1]="10.10.255.100"
SERVER_LOOPBACK_IP[HostB12_2]="10.10.255.101/32"; SERVER_ROUTER_ID[HostB12_2]="10.10.255.101"
# All servers share ASN 65200
for sv in Host12_1 Host12_2 Host12_3 Host34_1 Host34_2 HostB12_1 HostB12_2; do
    SERVER_BGP_ASN[$sv]=65200
done

# --- Server → Leaf peer ASN mapping ---
declare -A SERVER_PEER1_ASN SERVER_PEER2_ASN SERVER_PEER1_DESC SERVER_PEER2_DESC
SERVER_PEER1_ASN[Host12_1]=65011;  SERVER_PEER2_ASN[Host12_1]=65012
SERVER_PEER1_ASN[Host12_2]=65011;  SERVER_PEER2_ASN[Host12_2]=65012
SERVER_PEER1_ASN[Host12_3]=65011;  SERVER_PEER2_ASN[Host12_3]=65012
SERVER_PEER1_ASN[Host34_1]=65013;  SERVER_PEER2_ASN[Host34_1]=65014
SERVER_PEER1_ASN[Host34_2]=65013;  SERVER_PEER2_ASN[Host34_2]=65014
SERVER_PEER1_ASN[HostB12_1]=65021; SERVER_PEER2_ASN[HostB12_1]=65022
SERVER_PEER1_ASN[HostB12_2]=65021; SERVER_PEER2_ASN[HostB12_2]=65022
SERVER_PEER1_DESC[Host12_1]="Leaf_L1";  SERVER_PEER2_DESC[Host12_1]="Leaf_L2"
SERVER_PEER1_DESC[Host12_2]="Leaf_L1";  SERVER_PEER2_DESC[Host12_2]="Leaf_L2"
SERVER_PEER1_DESC[Host12_3]="Leaf_L1";  SERVER_PEER2_DESC[Host12_3]="Leaf_L2"
SERVER_PEER1_DESC[Host34_1]="Leaf_L3";  SERVER_PEER2_DESC[Host34_1]="Leaf_L4"
SERVER_PEER1_DESC[Host34_2]="Leaf_L3";  SERVER_PEER2_DESC[Host34_2]="Leaf_L4"
SERVER_PEER1_DESC[HostB12_1]="Border_Leaf1"; SERVER_PEER2_DESC[HostB12_1]="Border_Leaf2"
SERVER_PEER1_DESC[HostB12_2]="Border_Leaf1"; SERVER_PEER2_DESC[HostB12_2]="Border_Leaf2"

# ======================= UTILITY FUNCTIONS ==================================

# --- Target VM resolution ---
# Resolves user-supplied VM names/groups into a list of valid VM names
# Supports: individual names, groups (spines, leafs, border_leafs, servers, switches, all)
# Multiple VMs: comma-separated or space-separated
TARGET_VMS=()

resolve_targets() {
    local args=("$@")
    TARGET_VMS=()

    # If no targets specified, use all VMs
    if [[ ${#args[@]} -eq 0 ]]; then
        TARGET_VMS=("${VM_DEPLOY_ORDER[@]}")
        return 0
    fi

    for arg in "${args[@]}"; do
        # Split by comma if user passed "vm1,vm2,vm3"
        IFS=',' read -ra items <<< "$arg"
        for item in "${items[@]}"; do
            item=$(echo "$item" | xargs)  # trim whitespace
            case "${item,,}" in  # case-insensitive matching
                all)
                    TARGET_VMS=("${VM_DEPLOY_ORDER[@]}")
                    return 0
                    ;;
                spines)
                    TARGET_VMS+=(Spine_S1 Spine_S2)
                    ;;
                leafs|leaves)
                    TARGET_VMS+=(Leaf_L1 Leaf_L2 Leaf_L3 Leaf_L4)
                    ;;
                border_leafs|border-leafs|borders)
                    TARGET_VMS+=(Border_Leaf1 Border_Leaf2)
                    ;;
                switches|network)
                    TARGET_VMS+=(Spine_S1 Spine_S2 Leaf_L1 Leaf_L2 Leaf_L3 Leaf_L4 Border_Leaf1 Border_Leaf2)
                    ;;
                servers|hosts|compute)
                    TARGET_VMS+=(Host12_1 Host12_2 Host12_3 Host34_1 Host34_2 HostB12_1)
                    ;;
                router|exitrouter|exit_router|chr|routers)
                    TARGET_VMS+=(Exit_Router1 Exit_Router2)
                    ;;
                *)
                    # Try exact match first
                    if [[ -n "${VM_TYPE[$item]+x}" ]]; then
                        TARGET_VMS+=("$item")
                    else
                        # Try case-insensitive match against known VMs
                        local matched=false
                        for vm in "${VM_DEPLOY_ORDER[@]}"; do
                            if [[ "${vm,,}" == "${item,,}" ]]; then
                                TARGET_VMS+=("$vm")
                                matched=true
                                break
                            fi
                        done
                        if ! $matched; then
                            err "Unknown VM or group: '$item'"
                            err "Valid VMs: ${VM_DEPLOY_ORDER[*]}"
                            err "Valid groups: all, spines, leafs, border_leafs, switches, servers, router"
                            return 1
                        fi
                    fi
                    ;;
            esac
        done
    done

    # Remove duplicates while preserving order
    local -A seen
    local unique=()
    for vm in "${TARGET_VMS[@]}"; do
        if [[ -z "${seen[$vm]+x}" ]]; then
            seen[$vm]=1
            unique+=("$vm")
        fi
    done
    TARGET_VMS=("${unique[@]}")
    return 0
}

gen_mac() {
    echo "${1}${2}" | md5sum | sed 's/^\(..\)\(..\)\(..\)\(..\)\(..\).*$/52:54:00:\1:\2:\3/'
}

check_integrity() {
    local file="$1"
    [[ ! -f "$file" || ! -s "$file" ]] && return 1
    case "${file##*.}" in
        qcow2) qemu-img check "$file" >/dev/null 2>&1 ;;
        gz)    gzip -t "$file" 2>/dev/null ;;
        zip)   unzip -t "$file" >/dev/null 2>&1 ;;
        img)   qemu-img info "$file" >/dev/null 2>&1 ;;
        *)     return 0 ;;
    esac
}

check_sha256() {
    local file="$1" expected="$2"
    [[ -z "$expected" ]] && return 0
    local actual
    actual=$(sha256sum "$file" | awk '{print $1}')
    if [[ "$actual" == "$expected" ]]; then
        ok "SHA256 verified: ${file##*/}"
        return 0
    else
        err "SHA256 MISMATCH for ${file##*/}"
        err "  Expected: $expected"
        err "  Got:      $actual"
        return 1
    fi
}

download_safe() {
    # Proxy-aware download with wget/curl fallback and retry
    local url="$1" dest="$2" desc="${3:-file}"
    local attempt=1 max_retries=3

    [[ -f "$dest" ]] && check_integrity "$dest" && { ok "$desc already present."; return 0; }
    [[ -f "$dest" ]] && { warn "Removing corrupt $desc..."; rm -f "$dest"; }

    while [[ $attempt -le $max_retries ]]; do
        log "Downloading $desc (attempt $attempt/$max_retries)..."
        if command -v wget &>/dev/null; then
            if wget -e use_proxy=yes -e http_proxy="$HTTP_PROXY" -e https_proxy="$HTTPS_PROXY" \
                    --no-check-certificate -q --show-progress --content-disposition \
                    --timeout=120 --tries=2 -O "$dest" "$url" 2>&1; then
                check_integrity "$dest" && { ok "$desc downloaded."; return 0; }
            fi
        elif command -v curl &>/dev/null; then
            if curl -x "$HTTP_PROXY" -L --insecure -o "$dest" --connect-timeout 60 "$url" 2>&1; then
                check_integrity "$dest" && { ok "$desc downloaded."; return 0; }
            fi
        else
            die "Neither wget nor curl available."
        fi
        warn "Attempt $attempt failed for $desc — retrying..."
        rm -f "$dest"
        attempt=$((attempt + 1))
        sleep 5
    done
    err "Failed to download $desc after $max_retries attempts."
    return 1
}

check_and_install() {
    local cmd="$1" pkg="${2:-$1}"
    if ! command -v "$cmd" &>/dev/null; then
        log "Installing $pkg..."
        sudo apt-get install -y -qq "$pkg" 2>&1 | tail -1
    fi
}

# Remove stale vnet ports from OVS bridges (devices that no longer exist)
# This prevents "port vnetX is actually attached to bridge br-Y" errors
# when libvirt reuses vnet names for new VMs.
clean_stale_ovs_ports() {
    local cleaned=0
    local br port
    for br in $(sudo ovs-vsctl list-br 2>/dev/null || true); do
        for port in $(sudo ovs-vsctl list-ports "$br" 2>/dev/null || true); do
            # Only clean vnet* ports (libvirt-managed tap devices)
            [[ "$port" == vnet* ]] || continue
            # If the network device no longer exists, remove the stale port
            if [[ ! -e "/sys/class/net/${port}" ]]; then
                sudo ovs-vsctl --if-exists del-port "$br" "$port" 2>/dev/null || true
                cleaned=$((cleaned + 1))
            fi
        done
    done
    if [[ $cleaned -gt 0 ]]; then
        log "Cleaned $cleaned stale vnet port(s) from OVS bridges."
    fi
    return 0
}

force_delete_vm() {
    local name="$1"
    if sudo virsh dominfo "$name" &>/dev/null; then
        log "Force-deleting existing VM: $name"
        sudo virsh destroy "$name" 2>/dev/null || true
        # DO NOT use --remove-all-storage — it deletes shared backing images!
        sudo virsh undefine "$name" 2>/dev/null || true
        sudo rm -f "$DISK_DIR/${name}.qcow2" "$DISK_DIR/${name}.img"
        sudo rm -f "$CLOUD_INIT_DIR/${name}-cidata.iso"
        # Clean up any stale vnet ports left behind by the destroyed VM
        clean_stale_ovs_ports
    fi
}

# ======================= PHASE 0: PREREQUISITES =============================
phase0_setup() {
    header "PHASE 0: Prerequisites & Dependencies"
    mkdir -p "$IMG_DIR" "$TMP_DIR" "$DISK_DIR" "$CLOUD_INIT_DIR" "$PROJECT_ROOT"

    # --- Install required packages (only missing ones) ---
    local REQUIRED_PKGS=(
        libvirt-daemon-system libvirt-clients virtinst
        bridge-utils openvswitch-switch cloud-image-utils
        qemu-utils wget unzip openssh-client jq sshpass curl
        genisoimage
    )
    local to_install=()
    # qemu-kvm is transitional on Ubuntu 24.04; check for actual binary instead
    if ! command -v qemu-system-x86_64 &>/dev/null; then
        to_install+=("qemu-kvm")
    fi
    for pkg in "${REQUIRED_PKGS[@]}"; do
        if ! dpkg -l "$pkg" 2>/dev/null | grep -q "^ii"; then
            to_install+=("$pkg")
        fi
    done
    if [[ ${#to_install[@]} -gt 0 ]]; then
        log "Installing: ${to_install[*]}"
        sudo apt-get update -qq
        sudo apt-get install -y -qq "${to_install[@]}" 2>&1 | tail -3
        ok "Packages installed."
    else
        ok "All required packages present."
    fi

    # --- KVM check ---
    if [[ ! -e /dev/kvm ]]; then
        warn "/dev/kvm not found. Ensure .wslconfig has nestedVirtualization=true"
        die "Cannot continue without /dev/kvm."
    fi
    sudo chmod 666 /dev/kvm 2>/dev/null || true
    ok "KVM accessible."

    # --- Libvirt ---
    sudo service libvirtd start 2>/dev/null || sudo systemctl start libvirtd 2>/dev/null || true
    sudo service virtlogd start 2>/dev/null || sudo systemctl start virtlogd 2>/dev/null || true
    sleep 1
    sudo virsh list --all >/dev/null 2>&1 || die "Libvirt not responding."
    ok "Libvirt running."

    # --- Open vSwitch ---
    sudo service openvswitch-switch start 2>/dev/null || sudo systemctl start openvswitch-switch 2>/dev/null || true
    sleep 1
    sudo ovs-vsctl show >/dev/null 2>&1 || die "Open vSwitch not responding."
    ok "Open vSwitch running."

    # --- Permissions (user-centric approach from v8+) ---
    sudo chown -R "$USER":"$USER" "$IMG_DIR" "$TMP_DIR" "$DISK_DIR" "$CLOUD_INIT_DIR" 2>/dev/null || true
    chmod -R u+rwX "$IMG_DIR" "$TMP_DIR" "$DISK_DIR" "$CLOUD_INIT_DIR" 2>/dev/null || true
    ok "Permissions configured."
}

# ======================= PHASE 1: DOWNLOAD TO TMP ===========================
phase1_download() {
    header "PHASE 1: Download All Images to TMP"

    download_safe "$SONIC_URL" "$TMP_DIR/sonic-vs.img.gz" "SONiC VS (202405)" || \
        die "Cannot proceed without SONiC image."

    download_safe "$UBUNTU_URL" "$TMP_DIR/ubuntu_base.img" "Ubuntu Noble 24.04" || \
        die "Cannot proceed without Ubuntu image."

    download_safe "$CHR_URL" "$TMP_DIR/chr.zip" "MikroTik CHR 7.16" || \
        die "Cannot proceed without CHR image."

    # SHA256 verification for CHR
    check_sha256 "$TMP_DIR/chr.zip" "$CHR_SHA256" || \
        die "CHR image SHA256 mismatch — possible corruption or tampering."

    ok "All images downloaded to TMP."
}

# ======================= PHASE 2: VERIFY & PROCESS IMAGES ===================
phase2_process() {
    header "PHASE 2: Verify Integrity & Process Images"

    # Clear images dir for fresh state (v9 approach)
    log "Clearing images directory for fresh processing..."
    rm -rf "$IMG_DIR"/*

    # --- SONiC ---
    log "Processing SONiC image..."
    check_integrity "$TMP_DIR/sonic-vs.img.gz" || die "sonic-vs.img.gz is corrupt."
    gunzip -kf "$TMP_DIR/sonic-vs.img.gz"  # -k keeps the .gz

    # Detect actual format (SONiC VS .img is qcow2 despite the name)
    local sonic_src_fmt
    sonic_src_fmt=$(qemu-img info --output=json "$TMP_DIR/sonic-vs.img" | jq -r '.format')
    log "SONiC source format detected: $sonic_src_fmt"

    if [[ "$SONIC_DISK_FORMAT" == "qcow2" ]]; then
        if [[ "$sonic_src_fmt" == "qcow2" ]]; then
            # Already qcow2 — just copy (no lossy conversion)
            cp "$TMP_DIR/sonic-vs.img" "$IMG_DIR/sonic-vs.qcow2"
        else
            sudo qemu-img convert -f "$sonic_src_fmt" -O qcow2 "$TMP_DIR/sonic-vs.img" "$IMG_DIR/sonic-vs.qcow2"
        fi
    else
        if [[ "$sonic_src_fmt" == "raw" ]]; then
            cp "$TMP_DIR/sonic-vs.img" "$IMG_DIR/sonic-vs.img"
        else
            sudo qemu-img convert -f "$sonic_src_fmt" -O raw "$TMP_DIR/sonic-vs.img" "$IMG_DIR/sonic-vs.img"
        fi
    fi
    rm -f "$TMP_DIR/sonic-vs.img"
    ok "SONiC processed (format: $SONIC_DISK_FORMAT, source was: $sonic_src_fmt)."

    # --- Ubuntu ---
    log "Processing Ubuntu image..."
    check_integrity "$TMP_DIR/ubuntu_base.img" || die "Ubuntu image is corrupt."
    sudo qemu-img convert -f qcow2 -O qcow2 "$TMP_DIR/ubuntu_base.img" "$IMG_DIR/ubuntu-cloud.qcow2"
    ok "Ubuntu processed."

    # --- MikroTik CHR ---
    log "Processing MikroTik CHR image..."
    check_integrity "$TMP_DIR/chr.zip" || die "CHR zip is corrupt."
    unzip -qo "$TMP_DIR/chr.zip" -d "$TMP_DIR"
    local raw
    raw=$(find "$TMP_DIR" -maxdepth 1 -name "chr-*.img" | head -1)
    [[ -z "$raw" ]] && die "No chr-*.img found in zip."
    sudo qemu-img convert -f raw -O qcow2 "$raw" "$IMG_DIR/chr.qcow2"
    rm -f "$raw"
    ok "CHR processed."

    # --- Post-conversion integrity verification (from v9) ---
    log "Verifying converted images..."
    if [[ "$SONIC_DISK_FORMAT" == "qcow2" ]]; then
        check_integrity "$IMG_DIR/sonic-vs.qcow2" || die "SONiC qcow2 failed integrity check."
    fi
    check_integrity "$IMG_DIR/ubuntu-cloud.qcow2" || die "Ubuntu qcow2 failed integrity check."
    check_integrity "$IMG_DIR/chr.qcow2" || die "CHR qcow2 failed integrity check."

    # Fix permissions for libvirt
    sudo chmod -R o+rX "$IMG_DIR"
    ok "All images verified and ready."
}

# ======================= PHASE 3: NETWORKING ================================
phase3_networks() {
    header "PHASE 3: Create Management & Fabric Networks"

    # --- Management network (libvirt NAT) ---
    if ! sudo virsh net-info "$MGMT_NET_NAME" &>/dev/null; then
        log "Defining management network ($MGMT_NET_NAME)..."
        local net_xml="$TMP_DIR/net-mgmt.xml"
        cat > "$net_xml" <<XMLEOF
<network>
  <name>${MGMT_NET_NAME}</name>
  <forward mode='nat'/>
  <bridge name='br-mgmt' stp='on' delay='0'/>
  <ip address='${MGMT_NET_GW}' netmask='255.255.255.0'>
    <dhcp>
      <range start='${MGMT_DHCP_START}' end='${MGMT_DHCP_END}'/>
XMLEOF
        for vm in "${!VM_MGMT_IP[@]}"; do
            local mac
            mac=$(gen_mac "$vm" "mgmt")
            echo "      <host mac='${mac}' name='${vm}' ip='${VM_MGMT_IP[$vm]}'/>" >> "$net_xml"
        done
        cat >> "$net_xml" <<XMLEOF
    </dhcp>
  </ip>
</network>
XMLEOF
        sudo virsh net-define "$net_xml"
        sudo virsh net-start "$MGMT_NET_NAME"
        sudo virsh net-autostart "$MGMT_NET_NAME"
        ok "Management network created."
    else
        sudo virsh net-start "$MGMT_NET_NAME" 2>/dev/null || true
        # Sync DHCP host reservations (MACs may have changed since network was created)
        log "Syncing DHCP host reservations on existing network..."
        for vm in "${!VM_MGMT_IP[@]}"; do
            local mac
            mac=$(gen_mac "$vm" "mgmt")
            # Remove old entry (ignore errors if not present), then add current one
            sudo virsh net-update "$MGMT_NET_NAME" delete ip-dhcp-host \
                "<host name='${vm}'/>" --live --config 2>/dev/null || true
            sudo virsh net-update "$MGMT_NET_NAME" add ip-dhcp-host \
                "<host mac='${mac}' name='${vm}' ip='${VM_MGMT_IP[$vm]}'/>" \
                --live --config 2>/dev/null || true
        done
        ok "Management network active (DHCP reservations synced)."
    fi

    # --- Fabric OVS bridges ---
    log "Creating ${#FABRIC_BRIDGES[@]} OVS fabric bridges..."
    local created=0
    for br in "${FABRIC_BRIDGES[@]}"; do
        if ! sudo ovs-vsctl br-exists "$br" 2>/dev/null; then
            sudo ovs-vsctl add-br "$br"
            created=$((created + 1))
        fi
        # Enable LLDP/BPDUs forwarding — OVS drops IEEE reserved multicast
        # (01:80:c2:00:00:0e) by default, which blocks LLDP between SONiC VMs
        sudo ovs-vsctl set bridge "$br" other-config:forward-bpdu=true 2>/dev/null || true
    done
    ok "Fabric bridges: $created new, $((${#FABRIC_BRIDGES[@]} - created)) existing (forward-bpdu enabled)."

    # --- Libvirt network definitions for OVS bridges ---
    for br in "${FABRIC_BRIDGES[@]}"; do
        if ! sudo virsh net-info "$br" &>/dev/null; then
            cat > "$TMP_DIR/net-${br}.xml" <<BXML
<network>
  <name>${br}</name>
  <forward mode='bridge'/>
  <bridge name='${br}'/>
  <virtualport type='openvswitch'/>
</network>
BXML
            sudo virsh net-define "$TMP_DIR/net-${br}.xml"
            sudo virsh net-start "$br"
            sudo virsh net-autostart "$br"
        fi
    done
    ok "All libvirt OVS networks defined."

    # --- Clean stale vnet ports from previous failed/destroyed VMs ---
    clean_stale_ovs_ports
}

# ======================= PHASE 4: VM DEPLOYMENT =============================

create_cloud_init_iso() {
    local vm_name="$1" user="$2" pass="$3"
    local iso="$CLOUD_INIT_DIR/${vm_name}-cidata.iso"
    [[ -f "$iso" ]] && return 0

    # Cloud-init requires files named exactly "user-data" and "meta-data"
    # Use a per-VM temp directory to avoid collisions during parallel builds
    local ci_tmp="$TMP_DIR/ci-${vm_name}"
    mkdir -p "$ci_tmp"
    local md="$ci_tmp/meta-data"
    local ud="$ci_tmp/user-data"

    cat > "$md" <<EOF
instance-id: ${vm_name}
local-hostname: ${vm_name}
EOF

    cat > "$ud" <<EOF
#cloud-config
hostname: ${vm_name}
manage_etc_hosts: true
users:
  - name: ${user}
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    plain_text_passwd: '${pass}'
    shell: /bin/bash
ssh_pwauth: true
disable_root: false
chpasswd:
  expire: false
  list: |
    ${user}:${pass}
package_update: false
runcmd:
  - systemctl enable serial-getty@ttyS0.service || true
  - echo "Cloud-init complete for ${vm_name}" > /var/log/cloud-init-done
EOF

    # Network-config: only configure mgmt NIC via DHCP using match by MAC.
    # Without this, cloud-init waits for ALL NICs to come up, blocking boot
    # when fabric NICs have no DHCP server.
    # Note: Ubuntu Noble cloud images use predictable names (enp1s0, enp2s0...)
    # so we match by MAC address for portability.
    local nc="$ci_tmp/network-config"
    local mgmt_mac
    mgmt_mac=$(gen_mac "$vm_name" "mgmt")
    cat > "$nc" <<EOF
version: 2
ethernets:
  mgmt:
    match:
      macaddress: "${mgmt_mac}"
    dhcp4: true
EOF

    genisoimage -output "$iso" -volid cidata -joliet -rock "$ud" "$md" "$nc" 2>/dev/null
    rm -rf "$ci_tmp"
    sudo chmod o+r "$iso"
}

deploy_single_vm() {
    local name="$1"
    local type="${VM_TYPE[$name]}"
    local ram="${VM_RAM[$name]}"
    local vcpu="${VM_VCPU[$name]}"
    local bridges="${VM_BRIDGES[$name]:-}"
    local user="${VM_USER[$type]}"
    local pass="${VM_PASS[$type]}"

    # Skip if exists (unless --redeploy called force_delete first)
    if sudo virsh dominfo "$name" &>/dev/null; then
        local state
        state=$(sudo virsh domstate "$name" 2>/dev/null || echo "unknown")
        [[ "$state" == "shut off" ]] && sudo virsh start "$name" 2>/dev/null || true
        ok "$name exists (state: $state) — skipping."
        return 0
    fi

    log "Deploying $name [type=$type, ${ram}MB, ${vcpu}vCPU]..."

    # Determine base image and disk
    local base_img disk_path os_var backing_fmt extra_args=""
    case "$type" in
        sonic)
            if [[ "$SONIC_DISK_FORMAT" == "qcow2" ]]; then
                base_img="$IMG_DIR/sonic-vs.qcow2"; backing_fmt="qcow2"
            else
                base_img="$IMG_DIR/sonic-vs.img"; backing_fmt="raw"
            fi
            os_var="ubuntu20.04"
            # SONiC does NOT support cloud-init; uses ZTP for DHCP on eth0
            # Default credentials: admin / amolla01
            ;;
        ubuntu)
            base_img="$IMG_DIR/ubuntu-cloud.qcow2"; backing_fmt="qcow2"
            os_var="ubuntu24.04"
            create_cloud_init_iso "$name" "$user" "$pass"
            extra_args="--disk path=${CLOUD_INIT_DIR}/${name}-cidata.iso,device=cdrom"
            ;;
        chr)
            base_img="$IMG_DIR/chr.qcow2"; backing_fmt="qcow2"
            os_var="generic"
            # CHR does not support cloud-init
            ;;
    esac

    [[ ! -f "$base_img" ]] && { err "Base image missing: $base_img"; return 1; }

    # Create COW disk (thin provisioned, shares base)
    disk_path="$DISK_DIR/${name}.qcow2"
    sudo qemu-img create -f qcow2 -b "$base_img" -F "$backing_fmt" "$disk_path" 20G >/dev/null

    # Build NIC arguments: NIC0 = mgmt, NIC1+ = fabric
    # All NICs use virtio so mgmt NIC enumerates as eth0 (first PCI device)
    local mgmt_mac mgmt_model="virtio"
    # Note: e1000 was previously used for SONiC but causes eth ordering issues
    mgmt_mac=$(gen_mac "$name" "mgmt")
    local nic_args="--network network=${MGMT_NET_NAME},model=${mgmt_model},mac=${mgmt_mac}"

    if [[ -n "$bridges" ]]; then
        IFS=',' read -ra BR_LIST <<< "$bridges"
        local idx=0
        for br in "${BR_LIST[@]}"; do
            if [[ "$br" =~ ^@([0-9]+)$ ]]; then
                # @N = insert N real virtio NICs connected to the isolated br-pad
                # OVS bridge (no external peers).  Each NIC has a unique MAC and
                # consumes one NIC-index slot so that subsequent bridges land on
                # the correct port_config.ini index inside the SONiC KVM VS.
                # Example: @49 advances idx from 3 → 52 so that br-L1-S2/br-L1-S1
                # land on NIC53/NIC54 = Ethernet64/Ethernet68 (QSFP+5/6).
                # NOTE: --network none is virt-install's global "disable networking"
                # flag — it does NOT create a NIC — hence we use br-pad instead.
                local pad_count="${BASH_REMATCH[1]}"
                for ((pad=0; pad<pad_count; pad++)); do
                    local pad_mac
                    pad_mac=$(gen_mac "$name" "pad${idx}")
                    nic_args+=" --network network=br-pad,model=virtio,mac=${pad_mac}"
                    idx=$((idx + 1))
                done
            elif [[ "$br" == "none" ]]; then
                nic_args+=" --network none"
                idx=$((idx + 1))
            else
                local fab_mac
                fab_mac=$(gen_mac "$name" "fab${idx}")
                nic_args+=" --network network=${br},model=virtio,mac=${fab_mac}"
                idx=$((idx + 1))
            fi
        done
    fi

    # Deploy
    local virt_install_log="$TMP_DIR/${name}-virt-install.log"
    if sudo virt-install \
        --name "$name" \
        --ram "$ram" \
        --vcpus "$vcpu" \
        --disk path="$disk_path",format=qcow2,bus=virtio \
        $extra_args \
        --os-variant "$os_var" \
        $nic_args \
        --graphics none \
        --console pty,target_type=serial \
        --serial pty \
        --virt-type kvm \
        --import \
        --noautoconsole >"$virt_install_log" 2>&1; then
        ok "$name deployed. Console: sudo virsh console $name"
        rm -f "$virt_install_log"
    else
        err "$name deployment FAILED. virt-install output:"
        cat "$virt_install_log" | tee -a "$LOG_FILE"
        rm -f "$virt_install_log"
        sudo rm -f "$disk_path" "$CLOUD_INIT_DIR/${name}-cidata.iso"
        return 1
    fi
}

phase4_deploy() {
    header "PHASE 4: Deploy VMs"

    local vm_list=("${TARGET_VMS[@]}")
    local total=${#vm_list[@]} count=0 success=0 failed=0
    local total_ram=0
    for vm in "${vm_list[@]}"; do
        total_ram=$((total_ram + VM_RAM[$vm]))
    done
    log "Deploying $total VMs (total RAM: ${total_ram} MB)..."

    for vm in "${vm_list[@]}"; do
        if deploy_single_vm "$vm"; then
            success=$((success + 1))
        else
            failed=$((failed + 1))
        fi
        count=$((count + 1))
        printf "  ├─ Progress: %d/%d\n" "$count" "$total"
    done

    echo ""
    log "Deploy: $success OK, $failed FAILED out of $total."
    [[ $failed -gt 0 ]] && warn "Some VMs failed. Check errors above."
}

# ======================= PHASE 5: VALIDATION ================================
phase5_validate() {
    header "PHASE 5: SSH Connectivity Validation"

    local vm_list=("${TARGET_VMS[@]}")
    local boot_wait=180

    # If validating specific VMs (not full deploy), skip the long boot wait
    if [[ ${#vm_list[@]} -lt ${#VM_DEPLOY_ORDER[@]} ]]; then
        boot_wait=30
        log "Targeted validation (${#vm_list[@]} VMs) — waiting ${boot_wait}s..."
    else
        log "Waiting ${boot_wait}s for VMs to boot (SONiC needs ~2-3 min for ZTP/DHCP)..."
    fi
    sleep $boot_wait

    local pass=0 fail_count=0

    for vm in "${vm_list[@]}"; do
        local ip="${VM_MGMT_IP[$vm]}"
        local type="${VM_TYPE[$vm]}"
        local user="${VM_USER[$type]}"
        local pass_str="${VM_PASS[$type]}"
        local attempt=1 reachable=false

        printf "  %-18s (%s) " "$vm" "$ip"

        while [[ $attempt -le $SSH_MAX_RETRIES ]]; do
            if ping -c 1 -W 2 "$ip" &>/dev/null; then
                local ssh_opts="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=$SSH_TIMEOUT"
                local ssh_result=""
                if [[ -n "$pass_str" ]]; then
                    ssh_result=$(sshpass -p "$pass_str" ssh $ssh_opts "$user@$ip" "echo ok" 2>/dev/null || true)
                else
                    ssh_result=$(ssh $ssh_opts "$user@$ip" "echo ok" 2>/dev/null || true)
                fi
                if [[ "$ssh_result" == "ok" ]]; then
                    reachable=true
                    break
                fi
            fi
            printf "."
            attempt=$((attempt + 1))
            sleep $SSH_RETRY_DELAY
        done

        if $reachable; then
            echo -e " ${GRN}✓ SSH OK${RST}"
            pass=$((pass + 1))
        else
            if ping -c 1 -W 2 "$ip" &>/dev/null; then
                echo -e " ${YLW}△ PING OK (SSH not ready)${RST}"
                pass=$((pass + 1))
            else
                echo -e " ${RED}✗ UNREACHABLE${RST}"
                fail_count=$((fail_count + 1))
            fi
        fi
    done

    echo ""
    log "Validation: $pass reachable, $fail_count unreachable / ${#vm_list[@]} total."
}

# ======================= PHASE 5.5: SERVER POST-BOOT CONFIG =================
# Configures Ubuntu servers with:
#   - Virtio TX checksum offload fix (hypervisor-side)
#   - NAT masquerade for internet access (apt packages)
#   - FRR installation via proxy
#   - Netplan fabric interface configuration (BGP unnumbered)
#   - FRR BGP configuration with loopback announcement
#   - Loopback interface (lo) with routable IP
#
# This phase was added after discovering that deploy_lab_v13.sh originally
# deployed servers with management-only connectivity but no fabric config.
# The redeploy_hostb12.sh script was needed to fix this — now integrated.
# ==========================================================================

configure_server_virtio_fix() {
    # Disable TX checksum offload on tap interfaces connected to fabric bridges.
    # Without this fix, TCP (including BGP port 179) fails between VMs connected
    # through Linux/OVS bridges because virtio offloads checksum computation to
    # a physical NIC that doesn't exist in a virtual bridge path.
    local vm_name="$1"
    local bridges="${VM_BRIDGES[$vm_name]:-}"
    [[ -z "$bridges" ]] && return 0

    IFS=',' read -ra BR_LIST <<< "$bridges"
    local idx=0
    for br in "${BR_LIST[@]}"; do
        [[ "$br" =~ ^@[0-9]+$ || "$br" == "none" || "$br" == "br-pad" ]] && continue
        # Find tap interface attached to this bridge for this VM
        local tap
        tap=$(sudo ovs-vsctl list-ports "$br" 2>/dev/null | grep "^vnet" | while read -r port; do
            # Check if this tap belongs to our VM by examining the qemu process
            local vm_of_port
            vm_of_port=$(sudo virsh domiflist "$vm_name" 2>/dev/null | grep "$port" | head -1)
            [[ -n "$vm_of_port" ]] && echo "$port" && break
        done)
        if [[ -n "$tap" ]]; then
            sudo ethtool -K "$tap" tx off 2>/dev/null || true
        fi
        idx=$((idx + 1))
    done
}

configure_server_networking() {
    local vm_name="$1"
    local ip="${VM_MGMT_IP[$vm_name]}"
    local user="${VM_USER[ubuntu]}"
    local pass="${VM_PASS[ubuntu]}"
    local ssh_opts="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10"
    local loopback_ip="${SERVER_LOOPBACK_IP[$vm_name]:-}"
    local router_id="${SERVER_ROUTER_ID[$vm_name]:-}"
    local bgp_asn="${SERVER_BGP_ASN[$vm_name]:-65200}"
    local peer1_asn="${SERVER_PEER1_ASN[$vm_name]:-}"
    local peer2_asn="${SERVER_PEER2_ASN[$vm_name]:-}"
    local peer1_desc="${SERVER_PEER1_DESC[$vm_name]:-Peer1}"
    local peer2_desc="${SERVER_PEER2_DESC[$vm_name]:-Peer2}"

    [[ -z "$loopback_ip" ]] && { warn "$vm_name: No loopback IP defined, skipping FRR config"; return 0; }

    # Test SSH first
    local ssh_ok
    ssh_ok=$(sshpass -p "$pass" ssh $ssh_opts "$user@$ip" "echo ok" 2>/dev/null || true)
    [[ "$ssh_ok" != "ok" ]] && { warn "$vm_name: SSH not ready at $ip, skipping server config"; return 1; }

    log "  Configuring $vm_name ($ip) — loopback=$loopback_ip, ASN=$bgp_asn..."

    # Ubuntu Noble cloud images use predictable interface names:
    #   enp1s0 = NIC0 (mgmt), enp2s0 = NIC1 (fabric0), enp3s0 = NIC2 (fabric1)
    # Discover actual fabric interface names from the VM
    local fab0_name fab1_name
    fab0_name=$(sshpass -p "$pass" ssh $ssh_opts "$user@$ip" \
        "ip -o link show | grep -v lo | grep -v enp1s0 | awk -F': ' 'NR==1{print \$2}'" 2>/dev/null || echo "enp2s0")
    fab1_name=$(sshpass -p "$pass" ssh $ssh_opts "$user@$ip" \
        "ip -o link show | grep -v lo | grep -v enp1s0 | awk -F': ' 'NR==2{print \$2}'" 2>/dev/null || echo "enp3s0")

    # Configure proxy for apt (corporate network)
    sshpass -p "$pass" ssh $ssh_opts "$user@$ip" "sudo bash -c '
        mkdir -p /etc/apt/apt.conf.d
        echo \"Acquire::http::Proxy \\\"$HTTP_PROXY\\\";\" > /etc/apt/apt.conf.d/90proxy
        echo \"Acquire::https::Proxy \\\"$HTTPS_PROXY\\\";\" >> /etc/apt/apt.conf.d/90proxy
    '" 2>/dev/null || true

    # Install FRR
    sshpass -p "$pass" ssh $ssh_opts "$user@$ip" "
        if ! command -v vtysh &>/dev/null; then
            sudo apt-get update -qq 2>/dev/null
            sudo apt-get install -y -qq frr frr-pythontools 2>/dev/null
        fi
    " 2>/dev/null || { warn "$vm_name: FRR install failed (check proxy/internet)"; }

    # Configure loopback IP
    sshpass -p "$pass" ssh $ssh_opts "$user@$ip" "
        sudo ip addr add ${loopback_ip} dev lo 2>/dev/null || true
        # Make persistent via netplan drop-in
        sudo mkdir -p /etc/netplan
        sudo tee /etc/netplan/10-loopback.yaml > /dev/null <<LOEOF
network:
  version: 2
  ethernets:
    lo:
      addresses:
        - ${loopback_ip}
LOEOF
    " 2>/dev/null || true

    # Configure fabric interfaces (unnumbered — IPv6 link-local for BGP)
    sshpass -p "$pass" ssh $ssh_opts "$user@$ip" "
        sudo ip link set ${fab0_name} up 2>/dev/null || true
        sudo ip link set ${fab1_name} up 2>/dev/null || true
        # Add synthetic nexthop for BGP unnumbered compatibility with SONiC
        sudo ip addr add 169.254.0.1/32 dev ${fab0_name} 2>/dev/null || true
        sudo ip addr add 169.254.0.1/32 dev ${fab1_name} 2>/dev/null || true
        # Netplan for fabric interfaces
        sudo tee /etc/netplan/20-fabric.yaml > /dev/null <<FABEOF
network:
  version: 2
  ethernets:
    ${fab0_name}:
      dhcp4: false
      link-local: [ipv6]
      mtu: 9000
    ${fab1_name}:
      dhcp4: false
      link-local: [ipv6]
      mtu: 9000
FABEOF
        sudo netplan apply 2>/dev/null || true
    " 2>/dev/null || true

    # Configure FRR daemons file
    sshpass -p "$pass" ssh $ssh_opts "$user@$ip" "
        sudo sed -i 's/^bgpd=no/bgpd=yes/' /etc/frr/daemons 2>/dev/null || true
        sudo sed -i 's/^zebra=no/zebra=yes/' /etc/frr/daemons 2>/dev/null || true
    " 2>/dev/null || true

    # Deploy FRR configuration
    local frr_conf="frr version 8.4
frr defaults traditional
hostname ${vm_name}
log syslog informational
no ipv6 forwarding
!
router bgp ${bgp_asn}
 bgp router-id ${router_id}
 bgp bestpath as-path multipath-relax
 no bgp ebgp-requires-policy
 neighbor ${fab0_name} interface remote-as ${peer1_asn}
 neighbor ${fab0_name} description ${peer1_desc}
 neighbor ${fab1_name} interface remote-as ${peer2_asn}
 neighbor ${fab1_name} description ${peer2_desc}
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor ${fab0_name} activate
  neighbor ${fab0_name} soft-reconfiguration inbound
  neighbor ${fab1_name} activate
  neighbor ${fab1_name} soft-reconfiguration inbound
 exit-address-family
!
line vty
!"
    sshpass -p "$pass" ssh $ssh_opts "$user@$ip" "
        echo '${frr_conf}' | sudo tee /etc/frr/frr.conf > /dev/null
        sudo chown frr:frr /etc/frr/frr.conf
        sudo chmod 640 /etc/frr/frr.conf
        sudo systemctl restart frr
    " 2>/dev/null || { warn "$vm_name: FRR config deploy failed"; return 1; }

    ok "  $vm_name: FRR + loopback configured (${loopback_ip}, AS ${bgp_asn})"
}

phase5_5_server_config() {
    header "PHASE 5.5: Server Post-Boot Configuration (FRR + Loopback + Virtio Fix)"

    # Only configure Ubuntu servers that are in our target list
    local server_list=()
    for vm in "${TARGET_VMS[@]}"; do
        [[ "${VM_TYPE[$vm]}" == "ubuntu" ]] && server_list+=("$vm")
    done

    if [[ ${#server_list[@]} -eq 0 ]]; then
        log "No Ubuntu servers in target list — skipping server config phase."
        return 0
    fi

    # Enable NAT masquerade on hypervisor for server internet access (apt)
    log "Enabling NAT masquerade for management subnet..."
    if ! sudo iptables -t nat -C POSTROUTING -s 172.16.2.0/24 ! -d 172.16.2.0/24 -j MASQUERADE 2>/dev/null; then
        sudo iptables -t nat -A POSTROUTING -s 172.16.2.0/24 ! -d 172.16.2.0/24 -j MASQUERADE
        ok "NAT masquerade enabled for 172.16.2.0/24"
    else
        ok "NAT masquerade already active."
    fi

    # Apply virtio TX checksum fix for all target servers
    log "Applying virtio TX checksum offload fix on fabric tap interfaces..."
    for vm in "${server_list[@]}"; do
        configure_server_virtio_fix "$vm"
    done

    # Wait for servers to stabilize after boot
    log "Waiting 15s for server cloud-init to complete..."
    sleep 15

    # Configure each server with FRR + loopback
    local configured=0 failed=0
    for vm in "${server_list[@]}"; do
        if configure_server_networking "$vm"; then
            configured=$((configured + 1))
        else
            failed=$((failed + 1))
        fi
    done

    echo ""
    log "Server config: $configured OK, $failed FAILED out of ${#server_list[@]}."
    [[ $failed -gt 0 ]] && warn "Some servers failed configuration. Run: $0 validate servers"
}

# ======================= PHASE 5.6: KUBERNETES NODE PREPARATION =============
# Prepares Ubuntu servers for Kubernetes (Kubespray) installation.
# Profile-aware: only applies steps relevant to the deployment profile.
#
#   win11_kvm:       Full prep — Squid proxy (hypervisor), DNS, K8s packages,
#                    swap disable, kernel modules, sysctl. Proxy goes through
#                    the hypervisor's Squid (172.16.2.1:3128) which chains to
#                    corporate cso.proxy.att.com:8080.
#
#   ubuntu_r620_kvm: Full prep — Same as win11_kvm but uses direct corporate
#                    proxy (cso.proxy.att.com:8080). More RAM available so
#                    K8s resource limits can be higher.
#
#   real_hardware:   Minimal prep — Only kernel modules + sysctl + swap.
#                    Network, DNS, and proxy are pre-configured by infra team.
#                    Packages assumed installed from golden image or Satellite.
#
# Servers with K8S_ENABLED flag get prepared. By default only HostB12_1 is
# enabled, but any server can be flagged for K8s.
# ==========================================================================

# --- K8s-enabled servers (extend this map to add more K8s nodes) ---
declare -A K8S_ENABLED
K8S_ENABLED[HostB12_1]=true
# K8S_ENABLED[HostB12_2]=true    # Uncomment to add second K8s node
# K8S_ENABLED[Host34_1]=true     # Uncomment for worker in Pod 3-4

configure_server_k8s_proxy() {
    # Configure apt and environment proxy for K8s package downloads.
    # Only needed for KVM lab profiles where the hypervisor provides proxy.
    local vm_name="$1"
    local ip="${VM_MGMT_IP[$vm_name]}"
    local user="${VM_USER[ubuntu]}"
    local pass="${VM_PASS[ubuntu]}"
    local ssh_opts="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10"
    local proxy_url=""
    local no_proxy_addrs=""

    case "$AUTOMATION_PROFILE" in
        win11_kvm)
            # WSL2 lab: hypervisor runs Squid on 172.16.2.1:3128
            proxy_url="http://172.16.2.1:3128"
            no_proxy_addrs="localhost,127.0.0.1,172.16.2.0/24,192.168.255.0/25,10.233.0.0/18,10.233.64.0/18"
            ;;
        ubuntu_r620_kvm)
            # Dell R620: direct corporate proxy access
            proxy_url="http://cso.proxy.att.com:8080"
            no_proxy_addrs="localhost,127.0.0.1,172.16.2.0/24,10.233.0.0/18,10.233.64.0/18"
            ;;
        real_hardware)
            # Physical infra: proxy handled externally
            return 0
            ;;
    esac

    log "    [$vm_name] Configuring apt + environment proxy (${proxy_url})..."
    sshpass -p "$pass" ssh $ssh_opts "$user@$ip" "sudo bash -c '
        # Apt proxy
        mkdir -p /etc/apt/apt.conf.d
        cat > /etc/apt/apt.conf.d/90proxy <<PROXYEOF
Acquire::http::Proxy \"${proxy_url}\";
Acquire::https::Proxy \"${proxy_url}\";
PROXYEOF
        # Environment proxy (for pip, curl, wget, containerd pulls)
        grep -q \"http_proxy\" /etc/environment 2>/dev/null || cat >> /etc/environment <<ENVEOF
http_proxy=${proxy_url}
https_proxy=${proxy_url}
no_proxy=${no_proxy_addrs}
ENVEOF
    '" 2>/dev/null || { warn "$vm_name: proxy config failed"; return 1; }
}

configure_server_k8s_dns() {
    # Set DNS resolvers. Only needed for KVM lab profiles where VMs
    # have no upstream DNS configured by cloud-init beyond the hypervisor.
    local vm_name="$1"
    local ip="${VM_MGMT_IP[$vm_name]}"
    local user="${VM_USER[ubuntu]}"
    local pass="${VM_PASS[ubuntu]}"
    local ssh_opts="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10"

    case "$AUTOMATION_PROFILE" in
        real_hardware)
            # Physical infra: DNS pre-configured
            return 0
            ;;
    esac

    log "    [$vm_name] Setting DNS resolvers (8.8.8.8, 8.8.4.4)..."
    sshpass -p "$pass" ssh $ssh_opts "$user@$ip" \
        "sudo resolvectl dns enp1s0 8.8.8.8 8.8.4.4 2>/dev/null || true" 2>/dev/null
}

configure_server_k8s_packages() {
    # Install Kubernetes prerequisite packages.
    # Skipped for real_hardware (assumed pre-installed from golden image).
    local vm_name="$1"
    local ip="${VM_MGMT_IP[$vm_name]}"
    local user="${VM_USER[ubuntu]}"
    local pass="${VM_PASS[ubuntu]}"
    local ssh_opts="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10"

    case "$AUTOMATION_PROFILE" in
        real_hardware)
            log "    [$vm_name] Skipping package install (real_hardware profile)."
            return 0
            ;;
    esac

    log "    [$vm_name] Installing Kubernetes prerequisites..."
    sshpass -p "$pass" ssh $ssh_opts "$user@$ip" "
        sudo apt-get update -qq 2>/dev/null
        sudo apt-get install -y -qq \
            apt-transport-https ca-certificates curl gnupg lsb-release \
            conntrack socat ipset ipvsadm software-properties-common 2>/dev/null
    " 2>/dev/null || { warn "$vm_name: K8s package install had errors (check proxy)"; return 1; }
}

configure_server_k8s_swap() {
    # Disable swap (required by kubelet on all profiles).
    local vm_name="$1"
    local ip="${VM_MGMT_IP[$vm_name]}"
    local user="${VM_USER[ubuntu]}"
    local pass="${VM_PASS[ubuntu]}"
    local ssh_opts="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10"

    log "    [$vm_name] Disabling swap..."
    sshpass -p "$pass" ssh $ssh_opts "$user@$ip" "
        sudo swapoff -a
        sudo sed -i '/\sswap\s/d' /etc/fstab
    " 2>/dev/null || true
}

configure_server_k8s_kernel() {
    # Load kernel modules and set sysctl parameters for Kubernetes networking.
    # Required on ALL profiles (KVM and real hardware).
    local vm_name="$1"
    local ip="${VM_MGMT_IP[$vm_name]}"
    local user="${VM_USER[ubuntu]}"
    local pass="${VM_PASS[ubuntu]}"
    local ssh_opts="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10"

    log "    [$vm_name] Loading kernel modules + sysctl for K8s..."
    sshpass -p "$pass" ssh $ssh_opts "$user@$ip" "sudo bash -c '
        # Load modules now
        modprobe br_netfilter overlay ip_vs ip_vs_rr ip_vs_wrr ip_vs_sh 2>/dev/null

        # Persist modules across reboots
        cat > /etc/modules-load.d/k8s.conf <<MODEOF
br_netfilter
overlay
ip_vs
ip_vs_rr
ip_vs_wrr
ip_vs_sh
MODEOF

        # Sysctl for K8s networking
        cat > /etc/sysctl.d/99-kubernetes.conf <<SYSEOF
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
SYSEOF
        sysctl --system > /dev/null 2>&1
    '" 2>/dev/null || { warn "$vm_name: kernel module setup failed"; return 1; }
}

configure_server_k8s_node() {
    # Orchestrate all K8s preparation steps for a single server.
    # Steps are profile-aware — each function checks the profile internally.
    local vm_name="$1"
    local ip="${VM_MGMT_IP[$vm_name]}"
    local user="${VM_USER[ubuntu]}"
    local pass="${VM_PASS[ubuntu]}"
    local ssh_opts="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10"

    # Test SSH first
    local ssh_ok
    ssh_ok=$(sshpass -p "$pass" ssh $ssh_opts "$user@$ip" "echo ok" 2>/dev/null || true)
    if [[ "$ssh_ok" != "ok" ]]; then
        warn "$vm_name: SSH not ready at $ip, skipping K8s prep"
        return 1
    fi

    log "  Preparing $vm_name ($ip) for Kubernetes [profile=$AUTOMATION_PROFILE]..."

    configure_server_k8s_proxy "$vm_name"   || true
    configure_server_k8s_dns "$vm_name"     || true
    configure_server_k8s_packages "$vm_name" || true
    configure_server_k8s_swap "$vm_name"
    configure_server_k8s_kernel "$vm_name"  || return 1

    # Verification
    local verify_result
    verify_result=$(sshpass -p "$pass" ssh $ssh_opts "$user@$ip" "
        echo -n 'br_netfilter:'; lsmod | grep -qw br_netfilter && echo OK || echo MISSING
        echo -n 'ip_forward:'; cat /proc/sys/net/ipv4/ip_forward
        echo -n 'swap:'; free -h | grep -i swap | awk '{print \$2}'
    " 2>/dev/null || echo "verify failed")

    if echo "$verify_result" | grep -q "br_netfilter:OK"; then
        ok "  $vm_name: K8s node preparation complete."
        return 0
    else
        warn "$vm_name: Verification issues — $verify_result"
        return 1
    fi
}

phase5_6_k8s_prep() {
    header "PHASE 5.6: Kubernetes Node Preparation"

    # Filter target VMs to only K8s-enabled Ubuntu servers
    local k8s_servers=()
    for vm in "${TARGET_VMS[@]}"; do
        if [[ "${VM_TYPE[$vm]}" == "ubuntu" && "${K8S_ENABLED[$vm]:-false}" == "true" ]]; then
            k8s_servers+=("$vm")
        fi
    done

    if [[ ${#k8s_servers[@]} -eq 0 ]]; then
        log "No K8s-enabled servers in target list — skipping."
        log "  (To enable: set K8S_ENABLED[<server>]=true in script config)"
        return 0
    fi

    log "K8s-enabled servers: ${k8s_servers[*]}"
    log "Profile: $AUTOMATION_PROFILE"
    case "$AUTOMATION_PROFILE" in
        win11_kvm)      log "  Steps: proxy(squid) → DNS → packages → swap → kernel" ;;
        ubuntu_r620_kvm) log "  Steps: proxy(corporate) → DNS → packages → swap → kernel" ;;
        real_hardware)  log "  Steps: swap → kernel (proxy/DNS/packages skip)" ;;
    esac
    echo ""

    local configured=0 failed=0
    for vm in "${k8s_servers[@]}"; do
        if configure_server_k8s_node "$vm"; then
            configured=$((configured + 1))
        else
            failed=$((failed + 1))
        fi
    done

    echo ""
    log "K8s prep: $configured OK, $failed FAILED out of ${#k8s_servers[@]}."
    if [[ $configured -gt 0 ]]; then
        log "Next step: Run Kubespray to install K8s on prepared nodes."
        log "  cd ~/kubespray && ansible-playbook -i inventory/dc-lab/hosts.yml cluster.yml"
    fi
    [[ $failed -gt 0 ]] && warn "Some servers failed K8s prep. Check SSH and proxy connectivity."
}

# ======================= PHASE 6: ANSIBLE INVENTORY =========================
phase6_inventory() {
    header "PHASE 6: Generate Ansible Inventory & Validate Playbook"

    cat > "$INVENTORY_FILE" <<'HEAD'
---
# Auto-generated by deploy_lab_v13.sh — do not edit manually
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  children:
HEAD

    cat >> "$INVENTORY_FILE" <<EOF
    spines:
      vars:
        device_role: spine
        ansible_user: admin
        ansible_password: YourPaSsWoRd
        sonic_platform: "x86_64-kvm_x86_64-r0"
      hosts:
        Spine_S1: { ansible_host: "${VM_MGMT_IP[Spine_S1]}", router_id: "10.0.0.1", asn: 65100 }
        Spine_S2: { ansible_host: "${VM_MGMT_IP[Spine_S2]}", router_id: "10.0.0.2", asn: 65100 }
    leafs:
      vars:
        device_role: leaf
        ansible_user: admin
        ansible_password: YourPaSsWoRd
        sonic_platform: "x86_64-kvm_x86_64-r0"
      hosts:
        Leaf_L1: { ansible_host: "${VM_MGMT_IP[Leaf_L1]}", router_id: "10.0.0.11", asn: 65001 }
        Leaf_L2: { ansible_host: "${VM_MGMT_IP[Leaf_L2]}", router_id: "10.0.0.12", asn: 65002 }
        Leaf_L3: { ansible_host: "${VM_MGMT_IP[Leaf_L3]}", router_id: "10.0.0.13", asn: 65003 }
        Leaf_L4: { ansible_host: "${VM_MGMT_IP[Leaf_L4]}", router_id: "10.0.0.14", asn: 65004 }
    border_leafs:
      vars:
        device_role: border_leaf
        ansible_user: admin
        ansible_password: YourPaSsWoRd
        sonic_platform: "x86_64-kvm_x86_64-r0"
      hosts:
        Border_Leaf1: { ansible_host: "${VM_MGMT_IP[Border_Leaf1]}", router_id: "10.0.0.21", asn: 65021 }
        Border_Leaf2: { ansible_host: "${VM_MGMT_IP[Border_Leaf2]}", router_id: "10.0.0.22", asn: 65022 }
    exit_routers:
      vars:
        device_role: exit_router
        ansible_user: admin
        ansible_password: ""
      hosts:
        Exit_Router1: { ansible_host: "${VM_MGMT_IP[Exit_Router1]}", router_id: "10.0.0.253", asn: 65253, border_peer: Border_Leaf1 }
        Exit_Router2: { ansible_host: "${VM_MGMT_IP[Exit_Router2]}", router_id: "10.0.0.254", asn: 65254, border_peer: Border_Leaf2 }
    servers:
      vars:
        device_role: server
        ansible_user: ubuntu
        ansible_password: ubuntu
        ansible_become: true
      hosts:
        Host12_1: { ansible_host: "${VM_MGMT_IP[Host12_1]}", server_role: k8s_controller, leaf_pair: [Leaf_L1, Leaf_L2], loopback_ip: "${SERVER_LOOPBACK_IP[Host12_1]}", bgp_asn: 65200 }
        Host12_2: { ansible_host: "${VM_MGMT_IP[Host12_2]}", server_role: k8s_worker, leaf_pair: [Leaf_L1, Leaf_L2], loopback_ip: "${SERVER_LOOPBACK_IP[Host12_2]}", bgp_asn: 65200 }
        Host12_3: { ansible_host: "${VM_MGMT_IP[Host12_3]}", server_role: k8s_worker, leaf_pair: [Leaf_L1, Leaf_L2], loopback_ip: "${SERVER_LOOPBACK_IP[Host12_3]}", bgp_asn: 65200 }
        Host34_1: { ansible_host: "${VM_MGMT_IP[Host34_1]}", server_role: k8s_controller, leaf_pair: [Leaf_L3, Leaf_L4], loopback_ip: "${SERVER_LOOPBACK_IP[Host34_1]}", bgp_asn: 65200 }
        Host34_2: { ansible_host: "${VM_MGMT_IP[Host34_2]}", server_role: k8s_worker, leaf_pair: [Leaf_L3, Leaf_L4], loopback_ip: "${SERVER_LOOPBACK_IP[Host34_2]}", bgp_asn: 65200 }
        HostB12_1: { ansible_host: "${VM_MGMT_IP[HostB12_1]}", server_role: maas_controller, leaf_pair: [Border_Leaf1, Border_Leaf2], loopback_ip: "${SERVER_LOOPBACK_IP[HostB12_1]}", bgp_asn: 65200 }
        HostB12_2: { ansible_host: "${VM_MGMT_IP[HostB12_2]}", server_role: future, leaf_pair: [Border_Leaf1, Border_Leaf2], loopback_ip: "${SERVER_LOOPBACK_IP[HostB12_2]}", bgp_asn: 65200 }
    network:
      children:
        spines:
        leafs:
        border_leafs:
        exit_routers:
    compute:
      children:
        servers:
EOF

    ok "Inventory: $INVENTORY_FILE"

    # --- Generate SSH validation playbook ---
    cat > "$PROJECT_ROOT/validate_ssh.yml" <<'PLAYBOOK'
---
- name: Validate SSH connectivity to all lab nodes
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping test
      ansible.builtin.ping:
    - name: Gather hostname
      ansible.builtin.command: hostname
      register: result
    - name: Show hostname
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} reports: {{ result.stdout }}"
PLAYBOOK
    ok "Playbook: $PROJECT_ROOT/validate_ssh.yml"
    log "Run: ansible-playbook -i $INVENTORY_FILE $PROJECT_ROOT/validate_ssh.yml"
}

# ======================= TEARDOWN ==========================================
teardown() {
    header "TEARDOWN: Destroy All Lab Resources"
    echo -e "${RED}WARNING: This destroys ALL lab VMs, disks, and networks!${RST}"
    read -p "Type 'DESTROY' to confirm: " confirm
    [[ "$confirm" != "DESTROY" ]] && { log "Aborted."; exit 0; }

    for vm in "${VM_DEPLOY_ORDER[@]}"; do
        force_delete_vm "$vm"
    done
    ok "All VMs removed."

    for br in "${FABRIC_BRIDGES[@]}"; do
        sudo virsh net-destroy "$br" 2>/dev/null || true
        sudo virsh net-undefine "$br" 2>/dev/null || true
        sudo ovs-vsctl --if-exists del-br "$br" 2>/dev/null || true
    done
    sudo virsh net-destroy "$MGMT_NET_NAME" 2>/dev/null || true
    sudo virsh net-undefine "$MGMT_NET_NAME" 2>/dev/null || true
    ok "All networks removed."

    sudo rm -rf "$DISK_DIR"/* "$CLOUD_INIT_DIR"/*
    ok "Teardown complete. Images in $IMG_DIR preserved."
}

# ======================= STATUS REPORT ======================================
status_report() {
    header "LAB STATUS REPORT"
    printf "  ${BLD}%-18s %-10s %-16s %-8s %-6s${RST}\n" "VM" "STATE" "IP" "TYPE" "RAM"
    printf "  %-18s %-10s %-16s %-8s %-6s\n" "──────────────────" "──────────" "────────────────" "────────" "──────"

    local running=0 total_alloc=0
    for vm in "${VM_DEPLOY_ORDER[@]}"; do
        local state
        state=$(sudo virsh domstate "$vm" 2>/dev/null | tr -d '\n' || true)
        [[ -z "$state" ]] && state="undefined"
        local sc="$RST"
        case "$state" in running) sc="$GRN"; running=$((running+1)); total_alloc=$((total_alloc+VM_RAM[$vm])) ;; "shut off") sc="$YLW" ;; *) sc="$RED" ;; esac
        printf "  %-18s ${sc}%-10s${RST} %-16s %-8s %-6s\n" "$vm" "$state" "${VM_MGMT_IP[$vm]}" "${VM_TYPE[$vm]}" "${VM_RAM[$vm]}"
    done

    echo ""
    log "Running: $running/${#VM_DEPLOY_ORDER[@]} | RAM allocated: ${total_alloc} MB"
    echo ""
    log "OVS bridges: $(sudo ovs-vsctl list-br 2>/dev/null | wc -l) active"
}

# ======================= MAIN ===============================================
main() {
    echo "============================================================================"
    echo "  Data Center CLOS Lab Deployer v13.0"
    echo "  Generated by GitHub Copilot (Claude Opus 4.6) — $(date '+%Y-%m-%d %H:%M')"
    echo "============================================================================"

    # Ensure log directory exists
    mkdir -p "$(dirname "$LOG_FILE")"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --profile|-p)
                [[ $# -lt 2 ]] && die "--profile requires a value"
                AUTOMATION_PROFILE="$2"
                shift 2
                ;;
            *)
                break
                ;;
        esac
    done

    local action="${1:-deploy}"
    [[ $# -gt 0 ]] && shift

    if [[ -n "$AUTOMATION_PROFILE" ]]; then
        apply_profile_settings "$AUTOMATION_PROFILE"
    else
        prompt_for_profile
    fi
    initialize_vm_catalog
    print_profile_summary
    require_lab_profile "$action"

    # For 'test' action, don't resolve targets (it takes a type, not VM names)
    local _test_args=("$@")
    if [[ "$action" != "test" ]]; then
        resolve_targets "$@" || exit 1
        if [[ ${#TARGET_VMS[@]} -lt ${#VM_DEPLOY_ORDER[@]} && ${#TARGET_VMS[@]} -gt 0 ]]; then
            log "Target VMs: ${TARGET_VMS[*]}"
        fi
    fi

    case "$action" in
        deploy)
            phase0_setup
            phase1_download
            phase2_process
            phase3_networks
            phase4_deploy
            phase5_validate
            phase5_5_server_config
            phase5_6_k8s_prep
            phase6_inventory
            status_report
            echo ""
            log "═══ ALL PHASES COMPLETE ═══"
            log "Next: ansible-playbook -i $INVENTORY_FILE $PROJECT_ROOT/validate_ssh.yml"
            ;;
        redeploy|--redeploy)
            phase0_setup
            log "Force-deleting target VMs: ${TARGET_VMS[*]}"
            for vm in "${TARGET_VMS[@]}"; do force_delete_vm "$vm"; done
            phase1_download
            phase2_process
            phase3_networks
            phase4_deploy
            phase5_validate
            phase5_5_server_config
            phase5_6_k8s_prep
            phase6_inventory
            status_report
            ;;
        destroy|--destroy)
            if [[ ${#TARGET_VMS[@]} -lt ${#VM_DEPLOY_ORDER[@]} ]]; then
                # Targeted destroy — no confirmation needed
                log "Destroying target VMs: ${TARGET_VMS[*]}"
                for vm in "${TARGET_VMS[@]}"; do force_delete_vm "$vm"; done
                ok "Targeted destroy complete."
            else
                teardown
            fi
            ;;
        status|--status)
            status_report
            ;;
        images|--images)
            mkdir -p "$IMG_DIR" "$TMP_DIR"
            phase1_download
            phase2_process
            ;;
        validate|--validate)
            phase5_validate
            ;;
        ssh)
            # Quick SSH into a single VM
            if [[ ${#TARGET_VMS[@]} -ne 1 ]]; then
                die "ssh requires exactly one VM target. Usage: $0 ssh <vm_name>"
            fi
            local vm="${TARGET_VMS[0]}"
            local ip="${VM_MGMT_IP[$vm]}"
            local type="${VM_TYPE[$vm]}"
            local user="${VM_USER[$type]}"
            local pass="${VM_PASS[$type]}"

            # Pre-flight checks
            if ! sudo virsh dominfo "$vm" &>/dev/null; then
                err "$vm does not exist. Deploy it first:"
                die "  $0 deploy $vm"
            fi
            local vm_state
            vm_state=$(sudo virsh domstate "$vm" 2>/dev/null || echo "unknown")
            if [[ "$vm_state" != "running" ]]; then
                warn "$vm is '$vm_state'. Starting..."
                sudo virsh start "$vm" 2>/dev/null || die "Failed to start $vm."
                log "Waiting 30s for $vm to boot..."
                sleep 30
            fi
            if ! sudo virsh net-info "$MGMT_NET_NAME" &>/dev/null || \
               [[ "$(sudo virsh net-info "$MGMT_NET_NAME" 2>/dev/null | awk '/Active:/{print $2}')" != "yes" ]]; then
                err "Management network '$MGMT_NET_NAME' is not active."
                die "  Run: $0 deploy  (or manually: sudo virsh net-start $MGMT_NET_NAME)"
            fi
            if ! ping -c 2 -W 3 "$ip" &>/dev/null; then
                # Static IP unreachable — check DHCP leases for actual IP
                local lease_ip
                lease_ip=$(sudo virsh net-dhcp-leases "$MGMT_NET_NAME" 2>/dev/null | \
                    grep -i "${vm,,}\|${vm}" | awk '{print $5}' | sed 's|/.*||' | head -1)
                if [[ -n "$lease_ip" && "$lease_ip" != "$ip" ]]; then
                    warn "Static IP $ip unreachable, but DHCP lease found at $lease_ip"
                    warn "MAC reservation mismatch. Syncing now..."
                    local correct_mac
                    correct_mac=$(gen_mac "$vm" "mgmt")
                    sudo virsh net-update "$MGMT_NET_NAME" delete ip-dhcp-host \
                        "<host name='${vm}'/>" --live --config 2>/dev/null || true
                    sudo virsh net-update "$MGMT_NET_NAME" add ip-dhcp-host \
                        "<host mac='${correct_mac}' name='${vm}' ip='${VM_MGMT_IP[$vm]}'/>" \
                        --live --config 2>/dev/null || true
                    if ping -c 2 -W 3 "$lease_ip" &>/dev/null; then
                        log "Using current lease IP $lease_ip (will use $ip after VM renews DHCP)."
                        ip="$lease_ip"
                    else
                        err "$vm lease IP ($lease_ip) also not reachable."
                        err "  - VM may still be booting (SONiC needs ~2-3 min)"
                        err "  - Try console: $0 console $vm"
                        die "  Wait and retry, or validate: $0 validate $vm"
                    fi
                else
                    err "$vm ($ip) is not reachable via ping."
                    err "Possible causes:"
                    err "  - VM is still booting (SONiC needs ~2-3 min for ZTP/DHCP)"
                    err "  - DHCP lease not acquired (check: sudo virsh net-dhcp-leases $MGMT_NET_NAME)"
                    err "  - Try console: $0 console $vm"
                    die "  Wait and retry, or validate: $0 validate $vm"
                fi
            fi

            log "SSH → $vm ($user@$ip)..."
            if [[ -n "$pass" ]]; then
                sshpass -p "$pass" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$user@$ip"
            else
                ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$user@$ip"
            fi
            ;;
        console)
            # Quick console access to a single VM
            if [[ ${#TARGET_VMS[@]} -ne 1 ]]; then
                die "console requires exactly one VM target. Usage: $0 console <vm_name>"
            fi
            sudo virsh console "${TARGET_VMS[0]}"
            ;;
        test)
            # Deploy a single test VM of specified type for exploration
            # Usage: deploy_lab_v13.sh test sonic|ubuntu|chr
            local test_type="${_test_args[0]:-}"
            case "${test_type,,}" in
                sonic|ubuntu|chr) ;;
                *)
                    echo "Usage: $0 test <sonic|ubuntu|chr>"
                    echo ""
                    echo "Deploys a single test VM with management NIC only."
                    echo "After boot, auto-connects via SSH for exploration."
                    echo ""
                    echo "  $0 test sonic   — SONiC switch (admin/YourPaSsWoRd)"
                    echo "  $0 test ubuntu  — Ubuntu server (ubuntu/ubuntu)"
                    echo "  $0 test chr     — MikroTik CHR (admin/no password)"
                    exit 1
                    ;;
            esac

            local test_vm="Test_${test_type}"
            local test_ip="172.16.2.99"
            local test_ram test_user test_pass test_base test_fmt test_os mgmt_model="virtio"

            case "$test_type" in
                sonic)
                    test_ram=$SONIC_RAM; test_user="admin"; test_pass="YourPaSsWoRd"
                    mgmt_model="virtio"; test_os="ubuntu20.04"
                    if [[ "$SONIC_DISK_FORMAT" == "qcow2" ]]; then
                        test_base="$IMG_DIR/sonic-vs.qcow2"; test_fmt="qcow2"
                    else
                        test_base="$IMG_DIR/sonic-vs.img"; test_fmt="raw"
                    fi
                    ;;
                ubuntu)
                    test_ram=$SERVER_RAM; test_user="ubuntu"; test_pass="ubuntu"
                    test_os="ubuntu24.04"
                    test_base="$IMG_DIR/ubuntu-cloud.qcow2"; test_fmt="qcow2"
                    ;;
                chr)
                    test_ram=$CHR_RAM; test_user="admin"; test_pass=""
                    test_os="generic"
                    test_base="$IMG_DIR/chr.qcow2"; test_fmt="qcow2"
                    ;;
            esac

            header "TEST MODE: Single $test_type VM"
            log "VM: $test_vm | IP: $test_ip | Credentials: $test_user / ${test_pass:-<none>}"

            # Phase 0: prerequisites
            phase0_setup

            # Ensure images exist
            if [[ ! -f "$test_base" ]]; then
                phase1_download
                phase2_process
            fi
            [[ ! -f "$test_base" ]] && die "Base image missing: $test_base"

            # Ensure management network exists
            phase3_networks

            # Remove old test VM if exists
            force_delete_vm "$test_vm"

            # Add DHCP reservation for test VM
            local test_mac
            test_mac=$(gen_mac "$test_vm" "mgmt")
            sudo virsh net-update "$MGMT_NET_NAME" add ip-dhcp-host \
                "<host mac='${test_mac}' name='${test_vm}' ip='${test_ip}'/>" \
                --live --config 2>/dev/null || true

            # Create disk
            local test_disk="$DISK_DIR/${test_vm}.qcow2"
            sudo qemu-img create -f qcow2 -b "$test_base" -F "$test_fmt" "$test_disk" 20G >/dev/null

            # Cloud-init for Ubuntu only
            local extra_args=""
            if [[ "$test_type" == "ubuntu" ]]; then
                create_cloud_init_iso "$test_vm" "$test_user" "$test_pass"
                extra_args="--disk path=${CLOUD_INIT_DIR}/${test_vm}-cidata.iso,device=cdrom"
            fi

            # Deploy with mgmt NIC only (no fabric bridges)
            log "Deploying test VM..."
            if sudo virt-install \
                --name "$test_vm" \
                --ram "$test_ram" \
                --vcpus 2 \
                --disk path="$test_disk",format=qcow2,bus=virtio \
                $extra_args \
                --os-variant "$test_os" \
                --network network=${MGMT_NET_NAME},model=${mgmt_model},mac=${test_mac} \
                --graphics none \
                --console pty,target_type=serial \
                --serial pty \
                --virt-type kvm \
                --import \
                --noautoconsole >/dev/null 2>&1; then
                ok "$test_vm deployed successfully."
            else
                die "$test_vm deployment FAILED."
            fi

            # Wait and validate
            local wait_time=60
            [[ "$test_type" == "sonic" ]] && wait_time=180
            log "Waiting ${wait_time}s for $test_type to boot..."
            sleep $wait_time

            # SSH check
            local attempt=1 connected=false
            local ssh_opts="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5"
            log "Attempting SSH connection..."
            while [[ $attempt -le 15 ]]; do
                if ping -c 1 -W 2 "$test_ip" &>/dev/null; then
                    local result=""
                    if [[ -n "$test_pass" ]]; then
                        result=$(sshpass -p "$test_pass" ssh $ssh_opts "$test_user@$test_ip" "echo ok" 2>/dev/null || true)
                    else
                        result=$(ssh $ssh_opts "$test_user@$test_ip" "echo ok" 2>/dev/null || true)
                    fi
                    if [[ "$result" == "ok" ]]; then
                        connected=true
                        break
                    fi
                fi
                printf "."
                attempt=$((attempt + 1))
                sleep 10
            done
            echo ""

            if $connected; then
                ok "SSH connectivity verified!"
                echo ""
                echo "============================================================================"
                echo "  TEST VM READY"
                echo "============================================================================"
                echo "  Type:        $test_type"
                echo "  VM Name:     $test_vm"
                echo "  IP Address:  $test_ip"
                echo "  Username:    $test_user"
                echo "  Password:    ${test_pass:-<none>}"
                echo "  SSH:         ssh ${test_user}@${test_ip}"
                echo "  Console:     sudo virsh console $test_vm"
                echo "  Destroy:     sudo virsh destroy $test_vm && sudo virsh undefine $test_vm --remove-all-storage"
                echo "============================================================================"
                echo ""
                log "Connecting via SSH now... (type 'exit' to disconnect)"
                echo "────────────────────────────────────────────────────────────────────────────"
                if [[ -n "$test_pass" ]]; then
                    sshpass -p "$test_pass" ssh $ssh_opts "$test_user@$test_ip"
                else
                    ssh $ssh_opts "$test_user@$test_ip"
                fi
            else
                warn "SSH not reachable after retries."
                echo ""
                echo "  Try manually:"
                echo "    ssh ${test_user}@${test_ip}  (password: ${test_pass:-<none>})"
                echo "    sudo virsh console $test_vm"
                echo ""
                echo "  Destroy when done:"
                echo "    sudo virsh destroy $test_vm && sudo virsh undefine $test_vm --remove-all-storage"
            fi
            ;;
        *)
            echo "Usage: $0 [--profile <name>] <action> [vm1,vm2,...|group]"
            echo ""
            echo "Profiles:"
            echo "  win11_kvm        Windows 11 / WSL lab sizing"
            echo "  ubuntu_r620_kvm  Ubuntu / Dell R620 high-RAM lab sizing"
            echo "  real_hardware    Physical-switch workflow; skips KVM lab deployment"
            echo ""
            echo "Actions:"
            echo "  deploy    [targets] — Build VMs (idempotent, skips existing)"
            echo "  redeploy  [targets] — Force-delete + fresh deploy"
            echo "  destroy   [targets] — Tear down VMs (full teardown if no targets)"
            echo "  validate  [targets] — Re-run SSH connectivity checks"
            echo "  test      <type>    — Deploy single VM for testing (sonic|ubuntu|chr)"
            echo "  ssh       <vm>      — SSH directly into a VM"
            echo "  console   <vm>      — Attach virsh console to a VM"
            echo "  status              — Show all VM states + resource usage"
            echo "  images              — Download and verify images only"
            echo ""
            echo "Targets (optional, default=all):"
            echo "  Single:   Spine_S1, Leaf_L2, Host12_1, Exit_Router1"
            echo "  Multiple: Spine_S1,Leaf_L1,Host12_1  (comma-separated)"
            echo "  Groups:   spines, leafs, border_leafs, switches, servers, routers, all"
            echo ""
            echo "Examples:"
            echo "  $0 --profile win11_kvm deploy                    # Deploy all 16 VMs"
            echo "  $0 --profile ubuntu_r620_kvm redeploy spines     # Redeploy only Spine_S1 + Spine_S2"
            echo "  $0 --profile win11_kvm validate Leaf_L1,Leaf_L2  # Validate specific leafs"
            echo "  $0 --profile win11_kvm destroy servers           # Destroy only Ubuntu servers"
            echo "  $0 --profile ubuntu_r620_kvm deploy routers      # Deploy Exit_Router1 + Exit_Router2"
            echo "  $0 --profile win11_kvm test sonic                # Deploy single SONiC for testing"
            echo "  $0 --profile win11_kvm test ubuntu               # Deploy single Ubuntu for testing"
            echo "  $0 --profile win11_kvm test chr                  # Deploy single MikroTik for testing"
            echo "  $0 --profile win11_kvm ssh Spine_S1              # SSH into Spine_S1"
            echo "  $0 --profile win11_kvm console Exit_Router1      # Console into Exit_Router1"
            exit 1
            ;;
    esac
}

main "$@"
