#!/usr/bin/env python3
"""Customize config_db.json after sonic-cfggen generates it from port_config.ini.

Model: keep the full native platform port panel produced by the preset (all
ports remain, admin status from the preset) and only make the surgical edits
required by the topology:
  - Accton QSFP+ fabric: purge the 10G sibling sub-ports the native profile
    generates for the QSFP cages, then re-form clean 40G fabric ports. Leaving
    the siblings in place causes a duplicate-lane conflict that makes SONiC
    reject the config on `config reload` and revert to the stock 32-port image.
  - Arista QX breakout: any access index shared by >1 port is broken out
    (remove the parent, add the children) with a matching BREAKOUT_CFG entry.
"""
import json
from collections import defaultdict

with open('/tmp/port_data.json') as f:
    data = json.load(f)

switch_ports = data['switch_ports']
access_ports = data['access_ports']
meta = data['metadata']
target_hwsku = meta.get('hwsku', '')


def flatten_access_ports(raw_access_ports):
    """Normalize both legacy and breakout-aware access Ports into a list of child port definitions."""
    entries = []
    for port_name, cfg in raw_access_ports.items():
        if isinstance(cfg, dict) and 'children' in cfg and isinstance(cfg.get('children'), list):
            for child in cfg.get('children', []):
                child_cfg = dict(child)
                child_cfg.setdefault('name', child.get('name', port_name))
                entries.append(child_cfg)
        else:
            cfg_dict = dict(cfg) if isinstance(cfg, dict) else {}
            cfg_dict.setdefault('name', port_name)
            entries.append(cfg_dict)
    return entries


access_port_entries = flatten_access_ports(access_ports)

with open('/tmp/raw_config_db.json') as f:
    db = json.load(f)

# platform MUST stay x86_64-kvm_x86_64-r0: the ports come from the vendor
# port_config, but on a VM config reload can only load the kvm platform plugin;
# a real vendor platform value here makes the reload fail and revert to default.
db['DEVICE_METADATA']['localhost'].update({
    'hostname': meta['hostname'],
    'type': meta['type'],
    'router_id': meta['router_id'],
    'bgp_asn': meta['bgp_asn'],
    'platform': 'x86_64-kvm_x86_64-r0',
    'frr_mgmt_framework_config': 'true',
    'docker_routing_config_mode': 'unified'
})

# Remove preset-generated sections we don't need
for key in ['BGP_NEIGHBOR', 'DEVICE_NEIGHBOR', 'INTERFACE', 'LOOPBACK_INTERFACE']:
    db.pop(key, None)

# =========================================================================
# PLATFORM SPECIFIC: ACCTON SFP+ / QSFP+ FABRIC PRESERVATION
# =========================================================================
if "as5712" in target_hwsku.lower() or "accton" in target_hwsku.lower():
    # Force fabric ports back to original un-broken 40G bundling state
    # Overwrites the sonic-vs template which splits everything into 10G lines
    fabric_definitions = {
        "Ethernet64": {"lanes": "109,110,111,112", "index": "53", "speed": "40000"},
        "Ethernet68": {"lanes": "77,78,79,80",     "index": "54", "speed": "40000"}
    }

    # 1. Purge all child sub-interfaces generated by the native profile
    for i in range(64, 68):
        db['PORT'].pop(f"Ethernet{i}", None)
    for i in range(68, 72):
        db['PORT'].pop(f"Ethernet{i}", None)

    # 2. Inject clean, structured native 40G fabric interfaces
    for fname, fcfg in fabric_definitions.items():
        db['PORT'][fname] = {
            'lanes': fcfg['lanes'],
            'speed': fcfg['speed'],
            'index': fcfg['index'],
            'admin_status': 'up',
            'alias': fname,
            'mtu': '9100'
        }

# =========================================================================
# STANDARD BREAKOUT: For Arista QX models (multiple access ports on one index)
# =========================================================================
idx_groups = defaultdict(list)
for entry in access_port_entries:
    idx_groups[str(entry.get('index', entry.get('name')))] .append(entry.get('name'))

breakout_cfg = {}
for idx, ports in idx_groups.items():
    if len(ports) > 1:
        # Find and remove the parent port from PORT
        parent_name = None
        for pname, pcfg in list(db['PORT'].items()):
            if str(pcfg.get('index')) == idx:
                parent_name = pname
                break
        if parent_name and parent_name in db['PORT']:
            del db['PORT'][parent_name]

        # Add breakout children to PORT
        first_child = sorted(ports, key=lambda x: int(x.replace('Ethernet', '')))[0]
        child_speed = next((e.get('speed', '10000') for e in access_port_entries if e.get('name') == ports[0]), '10000')
        speed_g = int(child_speed) // 1000
        breakout_cfg[first_child] = {
            'brkout_mode': '%dx%dG[%dG]' % (len(ports), speed_g, speed_g)
        }
        for child in ports:
            ccfg = next((e for e in access_port_entries if e.get('name') == child), {})
            db['PORT'][child] = {
                'lanes': str(ccfg.get('lanes', '')),
                'speed': str(ccfg.get('speed', '10000')),
                'index': idx,
                'admin_status': 'up',
                'alias': ccfg.get('alias', child),
                'mtu': '9100'
            }

if breakout_cfg:
    db['BREAKOUT_CFG'] = breakout_cfg

# =========================================================================
# NORMALIZE: stamp the host_vars alias onto each port and keep ONLY the
# clab-connected ports admin up. Every other port on the vendor panel is
# forced admin down so the lab reflects the physical topology exactly.
# =========================================================================
port_meta = {}
port_meta.update(switch_ports)
for entry in access_port_entries:
    name = entry.get('name')
    if not name:
        continue
    port_meta[name] = {
        k: v for k, v in entry.items()
        if k in ('alias', 'role', 'speed', 'neighbor', 'neighbor_asn', 'peer', 'peer_port', 'rem_port', 'index', 'lanes')
    }

connected = set(switch_ports.keys())
for entry in access_port_entries:
    pname = entry.get('name')
    if not pname:
        continue

    # Only treat a breakout child as active when it has an actual peer.
    # A literal "neighbor: none" (or legacy "peer: none") means the port is
    # intentionally unused and must stay oper down even if the port object exists.
    neighbor = str(entry.get('neighbor') or entry.get('peer') or '').strip()
    neighbor_asn = entry.get('neighbor_asn')
    if neighbor_asn is not None and neighbor.lower() != 'none':
        connected.add(pname)

for pname, pcfg in db['PORT'].items():
    pcfg['admin_status'] = 'up' if pname in connected else 'down'
    pcfg.setdefault('mtu', '9100')  # jumbo frames on every port
    alias = port_meta.get(pname, {}).get('alias')
    if alias:
        pcfg['alias'] = alias

with open('/tmp/raw_config_db.json', 'w') as f:
    json.dump(db, f, indent=4)

