---
all:
  hosts:
    poweredge_r810:
      ansible_host: 192.168.9.198
      ansible_user: nh1221
      ansible_ssh_private_key_file: ~/.ssh/id_dc_lab
      # ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
      # ansible_ssh_common_args: '-o ProxyJump=nh1221@192.168.9.198:22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  children:
    # ==========================================================
    # PHASE 1 - UBUNTU WORKLOADS AND SERVERS (Group: linux)
    # ==========================================================
    linux:
      hosts:
        Host12-1:
          ansible_host: 172.16.2.51
        Host12-2:
          ansible_host: 172.16.2.52
        Host12-3:
          ansible_host: 172.16.2.53
        Host34-1:
          ansible_host: 172.16.2.54
        Host34-2:
          ansible_host: 172.16.2.55
        MonitorSrv:
          ansible_host: 172.16.2.56
        HostB12-1:
          ansible_host: 172.16.2.57
        HostB12-2:
          ansible_host: 172.16.2.58
        oob-mgmt-node:
          ansible_host: 172.16.2.254

    # ==========================================================
    # PHASE 2 - VENDOR-AGNOSTIC SONiC FABRICS (Group: sonic_vs)
    # ==========================================================
    sonic_vs:
      hosts:
        Spine-S1:
          ansible_host: 172.16.2.11
          hwsku: "Seastone-DX010" # Matches your verified command variable string
          sonic_platform_string: "x86_64-cel_seastone-r0"
          profile_subdir: "cel_seastone"
          port_config_path_suffix: "Seastone-DX010/port_config.ini"
        Spine-S2:
          ansible_host: 172.16.2.12
          hwsku: "Seastone-DX010"
          sonic_platform_string: "x86_64-cel_seastone-r0"
          profile_subdir: "cel_seastone"
          port_config_path_suffix: "Seastone-DX010/port_config.ini"
        Leaf-L1:
          ansible_host: 172.16.2.21
          hwsku: "Accton-AS5712-54X"
          sonic_platform_string: "x86_64-accton_as5712_54x-r0"
          profile_subdir: "accton_as5712"
          port_config_path_suffix: "Accton-AS5712-54X/port_config.ini"
        Leaf-L2:
          ansible_host: 172.16.2.22
          hwsku: "Accton-AS5712-54X"
          sonic_platform_string: "x86_64-accton_as5712_54x-r0"
          profile_subdir: "accton_as5712"
          port_config_path_suffix: "Accton-AS5712-54X/port_config.ini"
        Leaf-L3:
          ansible_host: 172.16.2.23
          hwsku: "Arista-7050-QX32"
          sonic_platform_string: "x86_64-arista_7050_qx32"
          profile_subdir: "arista_7050qx32"
          port_config_path_suffix: "Arista-7050-QX32/port_config.ini"
        Leaf-L4:
          ansible_host: 172.16.2.24
          hwsku: "Arista-7050-QX32"
          sonic_platform_string: "x86_64-arista_7050_qx32"
          profile_subdir: "arista_7050qx32"
          port_config_path_suffix: "Arista-7050-QX32/port_config.ini"
        Border-Leaf1:
          ansible_host: 172.16.2.31
          hwsku: "Arista-7050-QX-32S"
          sonic_platform_string: "x86_64-arista_7050_qx32s"
          profile_subdir: "arista_7050qx32s"
          port_config_path_suffix: "Arista-7050-QX-32S/port_config.ini"
        Border-Leaf2:
          ansible_host: 172.16.2.32
          hwsku: "Arista-7050-QX-32S"
          sonic_platform_string: "x86_64-arista_7050_qx32s"
          profile_subdir: "arista_7050qx32s"
          port_config_path_suffix: "Arista-7050-QX-32S/port_config.ini"

    # sonic_vs:
    #   hosts:
    #     Spine-S1:
    #       ansible_host: 172.16.2.11
    #       hwsku: "Celestica-DX010-C32"
    #       sonic_platform_string: "x86_64-cel_seastone-r0"
    #       profile_subdir: "cel_seastone"
    #     Spine-S2:
    #       ansible_host: 172.16.2.12
    #       hwsku: "Celestica-DX010-C32"
    #       sonic_platform_string: "x86_64-cel_seastone-r0"
    #       profile_subdir: "cel_seastone"
    #     Leaf-L1:
    #       ansible_host: 172.16.2.21
    #       hwsku: "Accton-AS5712-54X"
    #       sonic_platform_string: "x86_64-accton_as5712_54x-r0"
    #       profile_subdir: "accton_as5712"
    #     Leaf-L2:
    #       ansible_host: 172.16.2.22
    #       hwsku: "Accton-AS5712-54X"
    #       sonic_platform_string: "x86_64-accton_as5712_54x-r0"
    #       profile_subdir: "accton_as5712"
    #     Leaf-L3:
    #       ansible_host: 172.16.2.23
    #       hwsku: "Arista-7050QX-32"
    #       sonic_platform_string: "x86_64-arista_7050_qx32"
    #       profile_subdir: "arista_7050qx32"
    #     Leaf-L4:
    #       ansible_host: 172.16.2.24
    #       hwsku: "Arista-7050QX-32"
    #       sonic_platform_string: "x86_64-arista_7050_qx32"
    #       profile_subdir: "arista_7050qx32"
    #     Border-Leaf1:
    #       ansible_host: 172.16.2.31
    #       hwsku: "Arista-7050QX-32S"
    #       sonic_platform_string: "x86_64-arista_7050_qx32s"
    #       profile_subdir: "arista_7050qx32s"
    #     Border-Leaf2:
    #       ansible_host: 172.16.2.32
    #       hwsku: "Arista-7050QX-32S"
    #       sonic_platform_string: "x86_64-arista_7050_qx32s"
    #       profile_subdir: "arista_7050qx32s"

    # ==========================================================
    # PHASE 3 - EDGE WIREGUARD GATEWAYS (Group: exit_routers)
    # ==========================================================
    exit_routers:
      hosts:
        Exit-Router1:
          ansible_host: 172.16.2.41
        Exit-Router2:
          ansible_host: 172.16.2.42

    # ==========================================================
    # PHASE 4 - UPSTREAM ISP GATEWAYS (Group: isp_routers)
    # ==========================================================
    isp_routers:
      hosts:
        ISP1:
          ansible_host: 172.16.2.61
        ISP2:
          ansible_host: 172.16.2.62
