---
# sonic_server_net/handlers/main.yml

- name: restart_frr
  ansible.builtin.systemd:
    name: frr
    state: restarted
  become: true

- name: restart_networking
  ansible.builtin.command:
    cmd: netplan apply
  become: true
  changed_when: true
  failed_when: false
